LunarDrift/EntryPoint.cpp File Reference
#include `game/LunarDriftProgram.h`
*
#include `engine/containers/WindowPC.h`
*
#include `engine/exceptions/Exceptions.h`
*
#include <iostream>
*
Functions
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Function Documentation
int WINAPI WinMain (HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
Definition at line 7 of file EntryPoint.cpp.
References ShaderException::getComponent(), WindowPC::getContext(), ConfigurationException::getError(), FileIOException::getError(), ShaderException::getErrorLog(), UnsupportedFeatureException::getFeature(), FileIOException::getFile(), ShaderException::getFile(), OpenGLException::getGLErrorCode(), UnsupportedFeatureException::getReason(), OpenGLException::getReport(), ConfigurationException::getSetting(), ShaderException::getStage(), OpenGLException::glErrorCodeToString(), LunarDriftProgram::ms_Name, and WindowPC::run().