UnsupportedFeatureException Class Reference
Exception raised whenever a core feature is unsupported.
#include <UnsupportedFeatureException.h>
Public Member Functions
UnsupportedFeatureException (const std::string &feature, const std::string &reason)
Default constructor.
const std::string & getFeature () const
const std::string & getReason () const
Private Attributes
const std::string & m_Feature
const std::string & m_Reason
Detailed Description
Exception raised whenever a core feature is unsupported.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 12 of file UnsupportedFeatureException.h.
Constructor & Destructor Documentation
UnsupportedFeatureException::UnsupportedFeatureException (const std::string & feature, const std::string & reason)
Default constructor.
Parameters
feature Engine feature that's not supported.
reason The reason behind why they're not supported (optional).
Definition at line 3 of file UnsupportedFeatureException.cpp.
Member Function Documentation
const std::string& UnsupportedFeatureException::getFeature () const [inline]
Definition at line 25 of file UnsupportedFeatureException.h.
References m_Feature.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& UnsupportedFeatureException::getReason () const [inline]
Definition at line 27 of file UnsupportedFeatureException.h.
References m_Reason.
Referenced by WindowPC::renderingThread(), and WinMain().
Member Data Documentation
const std::string& UnsupportedFeatureException::m_Feature [private]
Definition at line 30 of file UnsupportedFeatureException.h.
Referenced by getFeature().
const std::string& UnsupportedFeatureException::m_Reason [private]
Definition at line 31 of file UnsupportedFeatureException.h.
Referenced by getReason().
The documentation for this class was generated from the following files:
LunarDrift/engine/exceptions/UnsupportedFeatureException.h
LunarDrift/engine/exceptions/UnsupportedFeatureException.cpp