TestTriangle Class Reference
#include <TestTriangle.h>
Public Member Functions
TestTriangle (Context *context, std::weak_ptr< MetaManager > managers)
Default constructor.
~TestTriangle ()
Default destructor.
void step (double dt) override
Step the simulation state.
void predraw (Context *context) override
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
void draw (Context *context, std::shared_ptr< ShaderManager > shaders) override
Draw the object in its current state.
void onMessage (std::shared_ptr< Message > event) override
Called when a subscribed event is raised.
Private Member Functions
void setupOutline (Context *context)
Private Attributes
std::shared_ptr< Model > m_Model
std::shared_ptr< Model > m_Outline
Additional Inherited Members
Detailed Description
Definition at line 7 of file TestTriangle.h.
Constructor & Destructor Documentation
TestTriangle::TestTriangle (Context * context, std::weak_ptr< MetaManager > managers)
Default constructor.
Definition at line 6 of file TestTriangle.cpp.
References SceneObject::addComponent(), Model::Vertex::color, f, MessageSystem::getInstance(), m_Model, Model::Vertex::position, setupOutline(), and MessageSystem::subscribe().
TestTriangle::~TestTriangle ()
Default destructor.
Definition at line 68 of file TestTriangle.cpp.
References MessageSystem::getInstance(), and MessageSystem::unsubscribe().
Member Function Documentation
void TestTriangle::draw (Context * context, std::shared_ptr< ShaderManager > shaders) [override], [virtual]
Draw the object in its current state.
Parameters
context Graphics context
shaders Shader manager containing shader programs for use
Implements SceneObject.
Definition at line 84 of file TestTriangle.cpp.
References m_Model, and m_Outline.
void TestTriangle::onMessage (std::shared_ptr< Message > event) [override], [virtual]
Called when a subscribed event is raised.
Parameters
event Smart pointer to the raised event object
Implements IMessageListener.
Definition at line 91 of file TestTriangle.cpp.
References SceneObject::setDying().
void TestTriangle::predraw (Context * context) [override], [virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Reimplemented from SceneObject.
Definition at line 79 of file TestTriangle.cpp.
References SceneObject::predraw().
void TestTriangle::setupOutline (Context * context) [private]
Definition at line 41 of file TestTriangle.cpp.
References Model::Vertex::color, f, Lines, m_Outline, and Model::Vertex::position.
Referenced by TestTriangle().
void TestTriangle::step (double dt) [override], [virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Reimplemented from SceneObject.
Definition at line 74 of file TestTriangle.cpp.
References SceneObject::step().
Member Data Documentation
std::shared_ptr<Model> TestTriangle::m_Model [private]
Definition at line 47 of file TestTriangle.h.
Referenced by draw(), and TestTriangle().
std::shared_ptr<Model> TestTriangle::m_Outline [private]
Definition at line 48 of file TestTriangle.h.
Referenced by draw(), and setupOutline().
The documentation for this class was generated from the following files:
LunarDrift/game/scenes/alphaspace/TestTriangle.h
LunarDrift/game/scenes/alphaspace/TestTriangle.cpp