IMessageListener Class Reference
Interface for handling messages sent from other entities.
#include <IMessageListener.h>
Public Member Functions
virtual ~IMessageListener ()
virtual void onMessage (std::shared_ptr< Message > msg)=0
Called when a message is sent to this entity.
Detailed Description
Interface for handling messages sent from other entities.
Messages are packets of data sent between entities in the program. Events operate in a broadcast fashion, messages operate in a unicast fashion with a sender and a receiver at the point of handling.
Author
Hayley Hatton
Date
10/03/2016
See also
Message
MessageSystem
Definition at line 18 of file IMessageListener.h.
Constructor & Destructor Documentation
virtual IMessageListener::~IMessageListener () [inline], [virtual]
Definition at line 21 of file IMessageListener.h.
References onMessage().
Member Function Documentation
virtual void IMessageListener::onMessage (std::shared_ptr< Message > msg) [pure virtual]
Called when a message is sent to this entity.
Parameters
msg Smart pointer to the received message object
Implemented in TestScene3D, LunarDriftProgram, TestTriangle, and HitpointComponent.
Referenced by LifeTimeComponent::step(), and ~IMessageListener().
The documentation for this class was generated from the following file:
LunarDrift/engine/comms/IMessageListener.h