SceneObjectManager Class Reference
A manager class for handling and passing around scene objects.
#include <SceneObjectManager.h>
Public Member Functions
SceneObjectManager ()
Default constructor.
~SceneObjectManager ()
Default destructor.
void addSceneObject (std::shared_ptr< SceneObject > object)
Add a scene object to the scene.
void removeSceneObject (std::shared_ptr< SceneObject > object)
Remove a scene object from the scene (and destroy if applicable)
void getObjects (std::list< std::shared_ptr< SceneObject >> *objects)
Retrieve the list of objects in the scene.
void step (double dt)
Step the scene's simulation state.
void predraw (Context *context)
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
Private Member Functions
void cleanupDyingObjects ()
Finalize the death and cleanup of objects marked as dying.
Private Attributes
std::list< std::shared_ptr< SceneObject > > m_SceneObjects
Detailed Description
A manager class for handling and passing around scene objects.
Author
Hayley Hatton
Date
11/03/2016
Definition at line 13 of file SceneObjectManager.h.
Constructor & Destructor Documentation
SceneObjectManager::SceneObjectManager ()
Default constructor.
Definition at line 4 of file SceneObjectManager.cpp.
SceneObjectManager::~SceneObjectManager ()
Default destructor.
Definition at line 8 of file SceneObjectManager.cpp.
Member Function Documentation
void SceneObjectManager::addSceneObject (std::shared_ptr< SceneObject > object)
Add a scene object to the scene.
Parameters
object Smart ptr to the scene object
Definition at line 13 of file SceneObjectManager.cpp.
References m_SceneObjects.
Referenced by Scene::addObject().
void SceneObjectManager::cleanupDyingObjects () [private]
Finalize the death and cleanup of objects marked as dying.
Definition at line 41 of file SceneObjectManager.cpp.
References SceneObject::Dying, and m_SceneObjects.
Referenced by predraw().
void SceneObjectManager::getObjects (std::list< std::shared_ptr< SceneObject >> * objects)
Retrieve the list of objects in the scene.
Parameters
objects Pointer to list to fill with scene objects
Definition at line 25 of file SceneObjectManager.cpp.
References m_SceneObjects.
Referenced by Scene::getObjects().
void SceneObjectManager::predraw (Context * context)
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Definition at line 57 of file SceneObjectManager.cpp.
References cleanupDyingObjects(), m_SceneObjects, and SceneObject::Ready.
Referenced by Scene::predraw().
void SceneObjectManager::removeSceneObject (std::shared_ptr< SceneObject > object)
Remove a scene object from the scene (and destroy if applicable)
Parameters
object Smart ptr to the scene object to remove
Definition at line 19 of file SceneObjectManager.cpp.
References m_SceneObjects.
void SceneObjectManager::step (double dt)
Step the scene's simulation state.
Parameters
dt Delta-time since last step call in seconds
Definition at line 31 of file SceneObjectManager.cpp.
References m_SceneObjects.
Referenced by Scene::step().
Member Data Documentation
std::list<std::shared_ptr<SceneObject> > SceneObjectManager::m_SceneObjects [private]
Definition at line 56 of file SceneObjectManager.h.
Referenced by addSceneObject(), cleanupDyingObjects(), getObjects(), predraw(), removeSceneObject(), and step().
The documentation for this class was generated from the following files:
LunarDrift/engine/managers/SceneObjectManager.h
LunarDrift/engine/managers/SceneObjectManager.cpp