VertexArrayObject Class Reference
A buffer object that aggregates VBOs, Vertex Attributes and IBOs.
#include <VertexArrayObject.h>
Public Member Functions
VertexArrayObject (Context *context, std::shared_ptr< VertexBufferObjectBase > vbo, const std::vector< VertexAttribute > &attributes, std::shared_ptr< IndexBufferObject > ibo=nullptr)
Constructs a VAO and associates it with the VBO and/or IBO.
virtual ~VertexArrayObject ()
Default destructor.
void setVertexBuffer (std::shared_ptr< VertexBufferObjectBase > vbo)
Associate a VertexBufferObject with the VAO.
std::shared_ptr< VertexBufferObjectBase > getVertexBuffer ()
Access the VertexBufferObject associated with the VAO.
void setAttributeMap (const std::vector< VertexAttribute > &attributes)
Set a new map of attributes to describe the associated vertex data.
const std::vector< VertexAttribute > & getAttributeMap () const
Access the map of attributes that describe the vertex data.
void setIndexBuffer (std::shared_ptr< IndexBufferObject > ibo)
Associate or disassociate an IndexBufferObject with the VAO.
std::shared_ptr< IndexBufferObject > getIndexBuffer ()
Access the IndexBufferObject associated with the VAO.
void bind (Context *context, std::shared_ptr< ShaderProgram > shader)
Bind the VAO to the OpenGL state pipeline.
Private Attributes
std::vector< VertexAttribute > m_Attributes
Attribute map for shaders.
std::shared_ptr< VertexBufferObjectBase > m_VertexBuffer
VBO ptr.
std::shared_ptr< IndexBufferObject > m_IndexBuffer
IBO ptr.
GLuint m_VAO
OpenGL-provided VAO handle.
Detailed Description
A buffer object that aggregates VBOs, Vertex Attributes and IBOs.
Precondition
A valid OpenGL context must be present to the program
Author
Hayley Hatton
Date
20/02/2016
See also
IndexBufferObject
VertexBufferObject
VertexAttribute
Definition at line 17 of file VertexArrayObject.h.
Constructor & Destructor Documentation
VertexArrayObject::VertexArrayObject (Context * context, std::shared_ptr< VertexBufferObjectBase > vbo, const std::vector< VertexAttribute > & attributes, std::shared_ptr< IndexBufferObject > ibo = nullptr)
Constructs a VAO and associates it with the VBO and/or IBO.
Parameters
context Graphics context
vbo Vertex buffer object ptr to associate with VAO
attributes Attribute map for describing vertex input to shaders
ibo Index buffer object ptr to associate with VAO
Definition at line 5 of file VertexArrayObject.cpp.
References m_VAO.
VertexArrayObject::~VertexArrayObject () [virtual]
Default destructor.
Definition at line 30 of file VertexArrayObject.cpp.
References m_VAO.
Member Function Documentation
void VertexArrayObject::bind (Context * context, std::shared_ptr< ShaderProgram > shader)
Bind the VAO to the OpenGL state pipeline.
Parameters
context Graphics context
shader Shader program to use with the VAO
Definition at line 54 of file VertexArrayObject.cpp.
References m_Attributes, m_IndexBuffer, m_VAO, and m_VertexBuffer.
Referenced by getIndexBuffer().
const std::vector<VertexAttribute>& VertexArrayObject::getAttributeMap () const [inline]
Access the map of attributes that describe the vertex data.
Returns
Vector of attribute descriptors
Definition at line 61 of file VertexArrayObject.h.
References m_Attributes, and setIndexBuffer().
std::shared_ptr<IndexBufferObject> VertexArrayObject::getIndexBuffer () [inline]
Access the IndexBufferObject associated with the VAO.
Returns
Smart ptr (or nullptr) to the underlying IndexBufferObject
Definition at line 75 of file VertexArrayObject.h.
References bind(), and m_IndexBuffer.
std::shared_ptr<VertexBufferObjectBase> VertexArrayObject::getVertexBuffer () [inline]
Access the VertexBufferObject associated with the VAO.
Returns
Smart ptr to the underlying VertexBufferObject
Definition at line 47 of file VertexArrayObject.h.
References m_VertexBuffer, and setAttributeMap().
void VertexArrayObject::setAttributeMap (const std::vector< VertexAttribute > & attributes)
Set a new map of attributes to describe the associated vertex data.
Parameters
attributes Attribute map for describing vertex input to shaders
Definition at line 36 of file VertexArrayObject.cpp.
References m_Attributes.
Referenced by getVertexBuffer().
void VertexArrayObject::setIndexBuffer (std::shared_ptr< IndexBufferObject > ibo)
Associate or disassociate an IndexBufferObject with the VAO.
Parameters
ibo IndexBufferObject ptr (or nullptr) to associate with the VAO
Definition at line 48 of file VertexArrayObject.cpp.
References m_IndexBuffer.
Referenced by getAttributeMap().
void VertexArrayObject::setVertexBuffer (std::shared_ptr< VertexBufferObjectBase > vbo)
Associate a VertexBufferObject with the VAO.
Parameters
vbo VertexBufferObject ptr to associate with the VAO
Definition at line 42 of file VertexArrayObject.cpp.
References m_VertexBuffer.
Member Data Documentation
std::vector<VertexAttribute> VertexArrayObject::m_Attributes [private]
Attribute map for shaders.
Definition at line 87 of file VertexArrayObject.h.
Referenced by bind(), getAttributeMap(), and setAttributeMap().
std::shared_ptr<IndexBufferObject> VertexArrayObject::m_IndexBuffer [private]
IBO ptr.
Definition at line 89 of file VertexArrayObject.h.
Referenced by bind(), getIndexBuffer(), and setIndexBuffer().
GLuint VertexArrayObject::m_VAO [private]
OpenGL-provided VAO handle.
Definition at line 90 of file VertexArrayObject.h.
Referenced by bind(), VertexArrayObject(), and ~VertexArrayObject().
std::shared_ptr<VertexBufferObjectBase> VertexArrayObject::m_VertexBuffer [private]
VBO ptr.
Definition at line 88 of file VertexArrayObject.h.
Referenced by bind(), getVertexBuffer(), and setVertexBuffer().
The documentation for this class was generated from the following files:
LunarDrift/engine/graphics/buffers/VertexArrayObject.h
LunarDrift/engine/graphics/buffers/VertexArrayObject.cpp