MessageSystem Class Reference
Singletonized central processing system for messages and events.
#include <MessageSystem.h>
Public Member Functions
void registerListener (const std::string &name, IMessageListener *listener)
Register a class instance as a message listener.
void unregisterListener (const std::string &name)
Unregister a message listener from being a listener.
void unregisterListener (IMessageListener *listener)
Unregister a class instance from being a listener.
void subscribe (const std::string &sevent, IMessageListener *listener)
Subscribe a class instance to receive events of a given name.
void unsubscribe (const std::string &sevent, IMessageListener *listener)
Unsubscribe a class instance from receiving events of a given name.
void broadcast (std::shared_ptr< Message > event)
Broadcast an event in the system to anyone interested.
void post (const std::string &to, std::shared_ptr< Message > msg)
Post a message to a registered listener.
void post (IMessageListener *listener, std::shared_ptr< Message > msg)
Post a message to a listener.
Static Public Member Functions
static MessageSystem & getInstance ()
Singleton access.
Private Member Functions
MessageSystem ()
MessageSystem (MessageSystem const &)=delete
void operator= (MessageSystem const &)=delete
Private Attributes
std::map< std::string, IMessageListener * > m_Listeners
std::map< std::string, std::list< IMessageListener * > > m_Subscribers
Detailed Description
Singletonized central processing system for messages and events.
This singleton encapsulates communication between entities in the program. Events and messages are dispatched through this class for dispatching to the relevant entities. For understanding, imagine if you will the idea of a post office, wherein letters and newspapers are posted through; this class is that post office. Consequently, its responsibilities include holding information on `subscriptions` (who is subscribed to set events) and storing names and addresses of `listeners` (for posting messages to), and processing the dispatching of events and messages to those interested, respectively.
Author
Hayley Hatton
Date
10/03/2016
See also
IMessageListener
Message
Definition at line 24 of file MessageSystem.h.
Constructor & Destructor Documentation
MessageSystem::MessageSystem () [inline], [private]
Definition at line 99 of file MessageSystem.h.
References operator=().
MessageSystem::MessageSystem (MessageSystem const &) [private], [delete]
Member Function Documentation
void MessageSystem::broadcast (std::shared_ptr< Message > event)
Broadcast an event in the system to anyone interested.
Parameters
event Smart pointer to event
Definition at line 46 of file MessageSystem.cpp.
References m_Subscribers.
Referenced by getInstance(), HitpointComponent::onMessage(), Keyboard::setKeyDown(), and Keyboard::setKeyUp().
static MessageSystem& MessageSystem::getInstance () [inline], [static]
Singleton access.
Definition at line 30 of file MessageSystem.h.
References broadcast(), post(), registerListener(), subscribe(), unregisterListener(), and unsubscribe().
Referenced by CollisionComponent::CollisionComponent(), HitpointComponent::HitpointComponent(), HitpointComponent::onMessage(), Keyboard::setKeyDown(), Keyboard::setKeyUp(), TestScene3D::TestScene3D(), TestTriangle::TestTriangle(), CollisionComponent::~CollisionComponent(), HitpointComponent::~HitpointComponent(), and TestTriangle::~TestTriangle().
void MessageSystem::operator= (MessageSystem const &) [private], [delete]
Referenced by MessageSystem().
void MessageSystem::post (const std::string & to, std::shared_ptr< Message > msg)
Post a message to a registered listener.
Parameters
to Name of the registered listener
msg Smart pointer to the message
Definition at line 57 of file MessageSystem.cpp.
References m_Listeners.
Referenced by getInstance().
void MessageSystem::post (IMessageListener * listener, std::shared_ptr< Message > msg)
Post a message to a listener.
Parameters
listener Pointer to the listener
msg Smart pointer to the message
Definition at line 62 of file MessageSystem.cpp.
void MessageSystem::registerListener (const std::string & name, IMessageListener * listener)
Register a class instance as a message listener.
Parameters
name Name for posting messages to
listener Pointer to class instance
Definition at line 3 of file MessageSystem.cpp.
References m_Listeners.
Referenced by getInstance().
void MessageSystem::subscribe (const std::string & sevent, IMessageListener * listener)
Subscribe a class instance to receive events of a given name.
Parameters
sevent Event name to subscribe to
listener Pointer to the class instance
Definition at line 26 of file MessageSystem.cpp.
References m_Subscribers.
Referenced by CollisionComponent::CollisionComponent(), getInstance(), HitpointComponent::HitpointComponent(), TestScene3D::TestScene3D(), and TestTriangle::TestTriangle().
void MessageSystem::unregisterListener (const std::string & name)
Unregister a message listener from being a listener.
Parameters
name Name of the listener
Definition at line 10 of file MessageSystem.cpp.
References m_Listeners.
Referenced by getInstance().
void MessageSystem::unregisterListener (IMessageListener * listener)
Unregister a class instance from being a listener.
Parameters
listener Class instance pointer
Definition at line 15 of file MessageSystem.cpp.
References m_Listeners.
void MessageSystem::unsubscribe (const std::string & sevent, IMessageListener * listener)
Unsubscribe a class instance from receiving events of a given name.
Parameters
sevent Event name to unsubscribe from
listener Pointer to the class instance
Definition at line 39 of file MessageSystem.cpp.
References m_Subscribers.
Referenced by getInstance(), CollisionComponent::~CollisionComponent(), HitpointComponent::~HitpointComponent(), and TestTriangle::~TestTriangle().
Member Data Documentation
std::map<std::string, IMessageListener*> MessageSystem::m_Listeners [private]
Definition at line 103 of file MessageSystem.h.
Referenced by post(), registerListener(), and unregisterListener().
std::map<std::string, std::list<IMessageListener*> > MessageSystem::m_Subscribers [private]
Definition at line 104 of file MessageSystem.h.
Referenced by broadcast(), subscribe(), and unsubscribe().
The documentation for this class was generated from the following files:
LunarDrift/engine/comms/MessageSystem.h
LunarDrift/engine/comms/MessageSystem.cpp