HitpointComponent Class Reference
#include <HitpointComponent.h>
Public Member Functions
HitpointComponent (SceneObject *parent, std::weak_ptr< MetaManager > managers, int hitpoints)
virtual ~HitpointComponent ()
void step (double dt) override
Step the simulation state.
void predraw (Context *context) override
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
void onMessage (std::shared_ptr< Message > msg) override
Called when a message is sent to this entity.
void setHitpoints (int hp)
int getHitpoints () const
void deductHitpoints (int hp)
int getMaxHitpoints () const
Private Attributes
int m_MaxHitpoints
int m_Hitpoints
Additional Inherited Members
Detailed Description
Definition at line 6 of file HitpointComponent.h.
Constructor & Destructor Documentation
HitpointComponent::HitpointComponent (SceneObject * parent, std::weak_ptr< MetaManager > managers, int hitpoints)
Definition at line 8 of file HitpointComponent.cpp.
References MessageSystem::getInstance(), and MessageSystem::subscribe().
HitpointComponent::~HitpointComponent () [virtual]
Definition at line 19 of file HitpointComponent.cpp.
References MessageSystem::getInstance(), and MessageSystem::unsubscribe().
Member Function Documentation
void HitpointComponent::deductHitpoints (int hp)
Definition at line 52 of file HitpointComponent.cpp.
References m_Hitpoints, and m_MaxHitpoints.
Referenced by getHitpoints(), and onMessage().
int HitpointComponent::getHitpoints () const [inline]
Definition at line 26 of file HitpointComponent.h.
References deductHitpoints(), and m_Hitpoints.
int HitpointComponent::getMaxHitpoints () const [inline]
Definition at line 30 of file HitpointComponent.h.
References m_MaxHitpoints.
void HitpointComponent::onMessage (std::shared_ptr< Message > msg) [override], [virtual]
Called when a message is sent to this entity.
Parameters
msg Smart pointer to the received message object
Implements IMessageListener.
Definition at line 25 of file HitpointComponent.cpp.
References MessageSystem::broadcast(), deductHitpoints(), MessageSystem::getInstance(), SceneObjectComponent::getParent(), and m_Hitpoints.
Referenced by predraw().
void HitpointComponent::predraw (Context * context) [inline], [override], [virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Implements SceneObjectComponent.
Definition at line 20 of file HitpointComponent.h.
References onMessage(), and setHitpoints().
void HitpointComponent::setHitpoints (int hp)
Definition at line 45 of file HitpointComponent.cpp.
References m_Hitpoints, and m_MaxHitpoints.
Referenced by predraw().
void HitpointComponent::step (double dt) [inline], [override], [virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Implements SceneObjectComponent.
Definition at line 18 of file HitpointComponent.h.
Member Data Documentation
int HitpointComponent::m_Hitpoints [private]
Definition at line 34 of file HitpointComponent.h.
Referenced by deductHitpoints(), getHitpoints(), onMessage(), and setHitpoints().
int HitpointComponent::m_MaxHitpoints [private]
Definition at line 33 of file HitpointComponent.h.
Referenced by deductHitpoints(), getMaxHitpoints(), and setHitpoints().
The documentation for this class was generated from the following files:
LunarDrift/engine/components/HitpointComponent.h
LunarDrift/engine/components/HitpointComponent.cpp