Context Class Reference
OpenGL context wrapper and provider.
#include <Context.h>
Public Member Functions
Context ()
Default constructor.
virtual ~Context ()
Default destructor.
void setDimensions (GLsizei width, GLsizei height)
Set the dimensions of the full rendering context.
void getDimensions (GLsizei *width, GLsizei *height) const
Access the dimensions of the full rendering context.
Private Attributes
GLsizei m_Width
GLsizei m_Height
Detailed Description
OpenGL context wrapper and provider.
This is practically empty due to the fact OpenGL's functions and context states are passed around through the thread stack, unlike Direct3D, which has ID3D11DeviceContext and related objects for accessing graphical API states and calls. However, this should be treated in a similar manner: do <u>not</u> call OpenGL functions unless a Context object is present. An exception can be made for Destructors, where parameters cannot be passed in, of course (just be sure to terminate objects on a thread with an OpenGL context available or OpenGL delete functions will crash!). Essentially: does the function or procedure have a non-null Context? If yes: safe to use OpenGL functions! If no: do so at your own risk.
Author
Hayley Hatton
Date
20/02/2016
See also
Renderer
Definition at line 24 of file Context.h.
Constructor & Destructor Documentation
Context::Context ()
Default constructor.
Definition at line 3 of file Context.cpp.
Context::~Context () [virtual]
Default destructor.
Definition at line 8 of file Context.cpp.
Member Function Documentation
void Context::getDimensions (GLsizei * width, GLsizei * height) const
Access the dimensions of the full rendering context.
Parameters
width Pointer to store width in pixels
height Pointer to store height in pixels
Definition at line 20 of file Context.cpp.
References m_Height, and m_Width.
Referenced by LunarDriftProgram::getRenderer(), and TestScene3D::TestScene3D().
void Context::setDimensions (GLsizei width, GLsizei height)
Set the dimensions of the full rendering context.
Parameters
width Width in pixels
height Height in pixels
Definition at line 14 of file Context.cpp.
References m_Height, and m_Width.
Referenced by WindowPC::createWindow(), and WindowPC::WindowPC().
Member Data Documentation
GLsizei Context::m_Height [private]
Definition at line 51 of file Context.h.
Referenced by getDimensions(), and setDimensions().
GLsizei Context::m_Width [private]
Definition at line 51 of file Context.h.
Referenced by getDimensions(), and setDimensions().
The documentation for this class was generated from the following files:
LunarDrift/engine/graphics/Context.h
LunarDrift/engine/graphics/Context.cpp