WindowPC Class Reference
Window class for use on Windows desktop PCs.
#include <WindowPC.h>
Classes
struct WIN32_EVENT
Public Member Functions
WindowPC (const std::string &title, HINSTANCE hInstance, LPSTR lpCmdLine, int nCmdShow, unsigned int width, unsigned int height)
Default constructor; sets up the environment.
virtual ~WindowPC ()
Default destructor.
Context * getContext ()
Access the underlying graphics context.
ExitStatus run (std::unique_ptr< Program > program) override
Running environment, with the final return status.
void simulationThread (Program *program)
Simulation thread function.
void renderingThread (Context *context, Program *program)
Rendering thread function.
Static Public Member Functions
static LRESULT CALLBACK WindowProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
Protected Member Functions
void preFrame (Context *context)
Do anything that needs to be done immediately before rendering.
void postFrame (Context *context)
Do anything that needs to be done immediately after rendering A prime example of this is the swapping of back-buffer to the display.
Private Member Functions
void postWin32EventToQueue (WIN32_EVENT &wievent)
void handleWin32EventQueue ()
void tempWindowStuff (const std::string &title, HINSTANCE hInstance)
void initGL (HWND hWnd, bool vSync=false)
HWND createWindow (const std::string &title, unsigned int width, unsigned int height, bool show, HINSTANCE hInstance)
HWND createWindow (const std::string &title, HINSTANCE hInstance)
void destroyWindow (HWND hWnd)
Private Attributes
HWND m_HWnd
HDC m_HDC
HGLRC m_HRC
std::queue< WIN32_EVENT > m_EventQueue
std::mutex m_EventMtx
Mutex for controlling queue access.
Context m_Context
Custom context.
bool m_Loaded
If false, constructor failed.
std::atomic< bool > m_Running
Whilst true, keep threads running.
Detailed Description
Window class for use on Windows desktop PCs.
Precondition
Win32 API support must be available to the compiler and running environments
Author
Hayley Hatton
Date
06/03/2016
Definition at line 17 of file WindowPC.h.
Constructor & Destructor Documentation
WindowPC::WindowPC (const std::string & title, HINSTANCE hInstance, LPSTR lpCmdLine, int nCmdShow, unsigned int width, unsigned int height)
Default constructor; sets up the environment.
Definition at line 10 of file WindowPC.cpp.
References createWindow(), Window::getGPUName(), initGL(), m_Context, m_HWnd, Context::setDimensions(), tempWindowStuff(), and WindowProc().
WindowPC::~WindowPC () [virtual]
Default destructor.
Definition at line 58 of file WindowPC.cpp.
References destroyWindow(), m_HDC, m_HRC, and m_HWnd.
Member Function Documentation
HWND WindowPC::createWindow (const std::string & title, unsigned int width, unsigned int height, bool show, HINSTANCE hInstance) [private]
Definition at line 74 of file WindowPC.cpp.
Referenced by tempWindowStuff(), and WindowPC().
HWND WindowPC::createWindow (const std::string & title, HINSTANCE hInstance) [private]
Definition at line 122 of file WindowPC.cpp.
References m_Context, and Context::setDimensions().
void WindowPC::destroyWindow (HWND hWnd) [private]
Definition at line 171 of file WindowPC.cpp.
Referenced by run(), tempWindowStuff(), and ~WindowPC().
Context* WindowPC::getContext () [inline]
Access the underlying graphics context.
Returns
Pointer to the underlying graphics context object
Definition at line 37 of file WindowPC.h.
References m_Context, postFrame(), preFrame(), renderingThread(), run(), simulationThread(), and WindowProc().
Referenced by WinMain().
void WindowPC::handleWin32EventQueue () [private]
Definition at line 408 of file WindowPC.cpp.
References InputMap::getInstance(), InputMap::getKeyboard(), m_EventQueue, WindowPC::WIN32_EVENT::message, Keyboard::setKeyDown(), Keyboard::setKeyUp(), and WindowPC::WIN32_EVENT::wParam.
Referenced by renderingThread().
void WindowPC::initGL (HWND hWnd, bool vSync = false) [private]
TODO: Multisampling!
Definition at line 238 of file WindowPC.cpp.
References addAttribute(), GLCONFIG_ALPHA_BITS, GLCONFIG_COLOR_BITS, GLCONFIG_DEPTH_BITS, GLCONFIG_MAJOR_VERSION, GLCONFIG_MINOR_VERSION, GLCONFIG_STENCIL_BITS, m_HDC, and m_HRC.
Referenced by WindowPC().
void WindowPC::postFrame (Context * context) [protected]
Do anything that needs to be done immediately after rendering A prime example of this is the swapping of back-buffer to the display.
Parameters
context Graphical context
Definition at line 397 of file WindowPC.cpp.
References m_HDC.
Referenced by getContext(), and renderingThread().
void WindowPC::postWin32EventToQueue (WIN32_EVENT & wievent) [private]
Definition at line 403 of file WindowPC.cpp.
References m_EventQueue.
Referenced by WindowProc().
void WindowPC::preFrame (Context * context) [protected]
Do anything that needs to be done immediately before rendering.
Parameters
context Graphical context
Definition at line 392 of file WindowPC.cpp.
Referenced by getContext(), and renderingThread().
void WindowPC::renderingThread (Context * context, Program * program)
Rendering thread function.
Parameters
context Graphical context
Definition at line 333 of file WindowPC.cpp.
References Program::frame(), ShaderException::getComponent(), ConfigurationException::getError(), FileIOException::getError(), ShaderException::getErrorLog(), UnsupportedFeatureException::getFeature(), FileIOException::getFile(), ShaderException::getFile(), OpenGLException::getGLErrorCode(), UnsupportedFeatureException::getReason(), OpenGLException::getReport(), ConfigurationException::getSetting(), ShaderException::getStage(), OpenGLException::glErrorCodeToString(), handleWin32EventQueue(), m_Running, postFrame(), and preFrame().
Referenced by getContext(), and run().
ExitStatus WindowPC::run (std::unique_ptr< Program > program) [override], [virtual]
Running environment, with the final return status.
Parameters
program Pointer to the program to run in the window
Returns
Status to exit application and return to desktop
Implements Window.
Definition at line 304 of file WindowPC.cpp.
References destroyWindow(), m_Context, m_HWnd, renderingThread(), simulationThread(), and Success.
Referenced by getContext(), and WinMain().
void WindowPC::simulationThread (Program * program)
Simulation thread function.
Definition at line 321 of file WindowPC.cpp.
References m_Running, and Program::step().
Referenced by getContext(), and run().
void WindowPC::tempWindowStuff (const std::string & title, HINSTANCE hInstance) [private]
Definition at line 176 of file WindowPC.cpp.
References createWindow(), and destroyWindow().
Referenced by WindowPC().
LRESULT CALLBACK WindowPC::WindowProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam) [static]
Definition at line 439 of file WindowPC.cpp.
References m_Running, and postWin32EventToQueue().
Referenced by getContext(), and WindowPC().
Member Data Documentation
Context WindowPC::m_Context [private]
Custom context.
Definition at line 90 of file WindowPC.h.
Referenced by createWindow(), getContext(), run(), and WindowPC().
std::mutex WindowPC::m_EventMtx [private]
Mutex for controlling queue access.
Definition at line 88 of file WindowPC.h.
std::queue<WIN32_EVENT> WindowPC::m_EventQueue [private]
Definition at line 87 of file WindowPC.h.
Referenced by handleWin32EventQueue(), and postWin32EventToQueue().
HDC WindowPC::m_HDC [private]
Definition at line 78 of file WindowPC.h.
Referenced by initGL(), postFrame(), and ~WindowPC().
HGLRC WindowPC::m_HRC [private]
Definition at line 79 of file WindowPC.h.
Referenced by initGL(), and ~WindowPC().
HWND WindowPC::m_HWnd [private]
Definition at line 77 of file WindowPC.h.
Referenced by run(), WindowPC(), and ~WindowPC().
bool WindowPC::m_Loaded [private]
If false, constructor failed.
Definition at line 91 of file WindowPC.h.
std::atomic<bool> WindowPC::m_Running [private]
Whilst true, keep threads running.
Definition at line 92 of file WindowPC.h.
Referenced by renderingThread(), simulationThread(), and WindowProc().
The documentation for this class was generated from the following files:
LunarDrift/engine/containers/WindowPC.h
LunarDrift/engine/containers/WindowPC.cpp