ShaderException Class Reference
Exception raised whenever a shader operation fails.
#include <ShaderException.h>
Public Member Functions
ShaderException (const std::string &file, const std::string &component, const std::string &stage, const std::string &errorLog)
Default constructor.
const std::string & getFile () const
const std::string & getComponent () const
const std::string & getStage () const
const std::string & getErrorLog () const
Private Attributes
const std::string m_File
const std::string m_Component
const std::string m_Stage
const std::string m_ErrorLog
Detailed Description
Exception raised whenever a shader operation fails.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 12 of file ShaderException.h.
Constructor & Destructor Documentation
ShaderException::ShaderException (const std::string & file, const std::string & component, const std::string & stage, const std::string & errorLog)
Default constructor.
Parameters
file File where the error was raised
component Shader component of the program where it went wrong
stage Stage of the shader pipeline where the error was raised
errorLog Generated error log
Definition at line 3 of file ShaderException.cpp.
Member Function Documentation
const std::string& ShaderException::getComponent () const [inline]
Definition at line 31 of file ShaderException.h.
References m_Component.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& ShaderException::getErrorLog () const [inline]
Definition at line 35 of file ShaderException.h.
References m_ErrorLog.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& ShaderException::getFile () const [inline]
Definition at line 29 of file ShaderException.h.
References m_File.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& ShaderException::getStage () const [inline]
Definition at line 33 of file ShaderException.h.
References m_Stage.
Referenced by WindowPC::renderingThread(), and WinMain().
Member Data Documentation
const std::string ShaderException::m_Component [private]
Definition at line 40 of file ShaderException.h.
Referenced by getComponent().
const std::string ShaderException::m_ErrorLog [private]
Definition at line 42 of file ShaderException.h.
Referenced by getErrorLog().
const std::string ShaderException::m_File [private]
Definition at line 39 of file ShaderException.h.
Referenced by getFile().
const std::string ShaderException::m_Stage [private]
Definition at line 41 of file ShaderException.h.
Referenced by getStage().
The documentation for this class was generated from the following files:
LunarDrift/engine/exceptions/ShaderException.h
LunarDrift/engine/exceptions/ShaderException.cpp