CollisionComponent Class Reference
Component that describes collision information about the parent.
#include <CollisionComponent.h>
Public Member Functions
CollisionComponent (SceneObject *parent, std::weak_ptr< MetaManager > managers, const glm::vec3 &topLeftOffset, const glm::vec3 &bottomRightOffset)
Default constructor.
~CollisionComponent ()
Default destructor.
void step (double dt) override
Step the simulation state.
void predraw (Context *context) override
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Additional Inherited Members
Detailed Description
Component that describes collision information about the parent.
This is currently setup to use Axis-Aligned Bounding Boxes, but the collision subsystem for it has been gutted.
Todo
Todo Setup collision geometry
Author
Hayley Hatton
Date
06/03/2016
See also
CollisionManager
Definition at line 17 of file CollisionComponent.h.
Constructor & Destructor Documentation
CollisionComponent::CollisionComponent (SceneObject * parent, std::weak_ptr< MetaManager > managers, const glm::vec3 & topLeftOffset, const glm::vec3 & bottomRightOffset)
Default constructor.
Parameters
parent Pointer to the scene object to attach component to
managers Metamanager for accessing scene's managers
Definition at line 7 of file CollisionComponent.cpp.
References MessageSystem::getInstance(), SceneObjectComponent::getParent(), CollisionManager::registerCollidable(), and MessageSystem::subscribe().
CollisionComponent::~CollisionComponent ()
Default destructor.
Definition at line 25 of file CollisionComponent.cpp.
References MessageSystem::getInstance(), SceneObjectComponent::getParent(), SceneObjectComponent::m_Managers, CollisionManager::unregisterCollidable(), and MessageSystem::unsubscribe().
Member Function Documentation
void CollisionComponent::predraw (Context * context) [inline], [override], [virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Implements SceneObjectComponent.
Definition at line 55 of file CollisionComponent.h.
void CollisionComponent::step (double dt) [inline], [override], [virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Implements SceneObjectComponent.
Definition at line 47 of file CollisionComponent.h.
The documentation for this class was generated from the following files:
LunarDrift/engine/components/CollisionComponent.h
LunarDrift/engine/components/CollisionComponent.cpp