CollisionManager Class Reference
A manager class for encapsulating collision detection processes.
#include <CollisionManager.h>
Public Member Functions
CollisionManager ()
Default constructor.
~CollisionManager ()
Default destructor.
void registerCollidable (std::weak_ptr< CollisionComponent > collidable)
Set a collision component to be checked for collisions.
void unregisterCollidable (std::weak_ptr< CollisionComponent > collidable)
Remove a collision component from being checked for collisions.
void doCollisions ()
Check for collisions and dispatch appropriate messages.
Private Attributes
std::list< std::weak_ptr< CollisionComponent > > m_Collidables
Detailed Description
A manager class for encapsulating collision detection processes.
Author
Hayley Hatton
Date
13/03/2016
See also
Scene
Definition at line 14 of file CollisionManager.h.
Constructor & Destructor Documentation
CollisionManager::CollisionManager ()
Default constructor.
Definition at line 6 of file CollisionManager.cpp.
CollisionManager::~CollisionManager ()
Default destructor.
Definition at line 10 of file CollisionManager.cpp.
Member Function Documentation
void CollisionManager::doCollisions ()
Check for collisions and dispatch appropriate messages.
Definition at line 38 of file CollisionManager.cpp.
References m_Collidables.
Referenced by Scene::step().
void CollisionManager::registerCollidable (std::weak_ptr< CollisionComponent > collidable)
Set a collision component to be checked for collisions.
Parameters
collidable Reference to a component for describing collisions
Definition at line 15 of file CollisionManager.cpp.
References m_Collidables.
Referenced by CollisionComponent::CollisionComponent().
void CollisionManager::unregisterCollidable (std::weak_ptr< CollisionComponent > collidable)
Remove a collision component from being checked for collisions.
Parameters
collidable Reference to a component for describing collisions
Definition at line 21 of file CollisionManager.cpp.
References c, and m_Collidables.
Referenced by CollisionComponent::~CollisionComponent().
Member Data Documentation
std::list<std::weak_ptr<CollisionComponent> > CollisionManager::m_Collidables [private]
Definition at line 45 of file CollisionManager.h.
Referenced by doCollisions(), registerCollidable(), and unregisterCollidable().
The documentation for this class was generated from the following files:
LunarDrift/engine/managers/CollisionManager.h
LunarDrift/engine/managers/CollisionManager.cpp