ConfigurationException Class Reference
Exception raised whenever a configuration setting is exceptional.
#include <ConfigurationException.h>
Public Member Functions
ConfigurationException (const std::string &setting, const std::string &err)
Default constructor.
const std::string & getSetting () const
const std::string & getError () const
Protected Attributes
const std::string m_Setting
const std::string m_Error
Detailed Description
Exception raised whenever a configuration setting is exceptional.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 12 of file ConfigurationException.h.
Constructor & Destructor Documentation
ConfigurationException::ConfigurationException (const std::string & setting, const std::string & err)
Default constructor.
Parameters
setting Configuration setting at fault
err Error string
Definition at line 3 of file ConfigurationException.cpp.
Member Function Documentation
const std::string& ConfigurationException::getError () const [inline]
Definition at line 25 of file ConfigurationException.h.
References m_Error.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& ConfigurationException::getSetting () const [inline]
Definition at line 23 of file ConfigurationException.h.
References m_Setting.
Referenced by WindowPC::renderingThread(), and WinMain().
Member Data Documentation
const std::string ConfigurationException::m_Error [protected]
Definition at line 29 of file ConfigurationException.h.
Referenced by getError().
const std::string ConfigurationException::m_Setting [protected]
Definition at line 28 of file ConfigurationException.h.
Referenced by getSetting().
The documentation for this class was generated from the following files:
LunarDrift/engine/exceptions/ConfigurationException.h
LunarDrift/engine/exceptions/ConfigurationException.cpp