Camera Class Reference
Describes a camera for viewing a scene.
#include <Camera.h>
Public Member Functions
Camera (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ)
Create a camera with an orthogonal lens.
Camera (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ, GLfloat fovy)
Create a camera with a perspective lens.
virtual ~Camera ()
Default destructor.
void setOrthogonal (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ)
Set an orthogonal lens for the camera.
void setPerspective (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ, GLfloat fovy)
Set a perspective lens for the camera.
void lookAt (const glm::vec3 &eye, const glm::vec3 &focus, const glm::vec3 &up)
Set the camera in the scene using classic `look-at` descriptors.
void pan (const glm::vec3 &dp)
Pan the camera.
void rotateX (GLfloat theta)
Rotate through the Y-Z plane (`X-axis`/`pitch`)
void rotateY (GLfloat theta)
Rotate through the X-Z plane (`Y-axis`/`yaw`)
void rotateZ (GLfloat theta)
Rotate through the X-Y plane (`Z-axis`/`roll`)
const glm::vec3 & getPosition () const
Access the position of the camera.
const glm::mat4 & getViewMatrix () const
Access the current view matrix state.
const glm::mat4 & getProjectionMatrix () const
Access the current projection matrix state.
void apply (Context *context, ShaderProgram *shader) const
Upload the camera matrices to a given shader program's uniforms.
void apply (Context *context, ShaderUniformBlock *buffer) const
Upload the camera matrices to a uniform buffer across all shaders.
Private Attributes
glm::mat4 m_ViewMatrix
Current view matrix state.
glm::mat4 m_ProjMatrix
Current projection matrix state.
Detailed Description
Describes a camera for viewing a scene.
Author
Hayley Hatton
Date
07/03/2016
Definition at line 13 of file Camera.h.
Constructor & Destructor Documentation
Camera::Camera (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ)
Create a camera with an orthogonal lens.
Parameters
width Width of the viewport
height Height of the viewport
nearZ Near-plane Z coordinate
farZ Far-plane Z coordinate
Definition at line 5 of file Camera.cpp.
References setOrthogonal().
Camera::Camera (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ, GLfloat fovy)
Create a camera with a perspective lens.
Parameters
width Width of the viewport
height Height of the viewport
nearZ Near-plane Z coordinate
farZ Far-plane Z coordinate
fovy Field-of-view, in degrees
Definition at line 12 of file Camera.cpp.
References setPerspective().
Camera::~Camera () [virtual]
Default destructor.
Definition at line 20 of file Camera.cpp.
Member Function Documentation
void Camera::apply (Context * context, ShaderProgram * shader) const
Upload the camera matrices to a given shader program's uniforms.
Parameters
context Graphics context
shader Ptr to the shader program to upload matrices to
Definition at line 76 of file Camera.cpp.
References ShaderProgram::getUniformLocation(), m_ProjMatrix, m_ViewMatrix, and ShaderProgram::use().
Referenced by getProjectionMatrix().
void Camera::apply (Context * context, ShaderUniformBlock * buffer) const
Upload the camera matrices to a uniform buffer across all shaders.
Parameters
context Graphics context
shader Ptr to the uniform buffer to upload matrices to
Todo
Todo (Hayley#6#03/08/16): Uploading of camera state to shader uniform blocks
Definition at line 95 of file Camera.cpp.
const glm::vec3& Camera::getPosition () const
Access the position of the camera.
Returns
3-component vector of the position in space
const glm::mat4& Camera::getProjectionMatrix () const [inline]
Access the current projection matrix state.
Returns
Projection matrix (4x4)
Definition at line 117 of file Camera.h.
References apply(), and m_ProjMatrix.
const glm::mat4& Camera::getViewMatrix () const [inline]
Access the current view matrix state.
Returns
View matrix (4x4)
Definition at line 111 of file Camera.h.
References m_ViewMatrix.
void Camera::lookAt (const glm::vec3 & eye, const glm::vec3 & focus, const glm::vec3 & up)
Set the camera in the scene using classic `look-at` descriptors.
Parameters
eye Position of the camera in the scene
focus Where the camera is looking at in the scene
up Up-vector defining the orientation of the camera
Definition at line 48 of file Camera.cpp.
References m_ViewMatrix.
void Camera::pan (const glm::vec3 & dp)
Pan the camera.
Parameters
dp Delta-position
Definition at line 56 of file Camera.cpp.
References m_ViewMatrix.
void Camera::rotateX (GLfloat theta)
Rotate through the Y-Z plane (`X-axis`/`pitch`)
Parameters
theta Angle in degrees through which to rotate the camera
Definition at line 61 of file Camera.cpp.
References f, and m_ViewMatrix.
void Camera::rotateY (GLfloat theta)
Rotate through the X-Z plane (`Y-axis`/`yaw`)
Parameters
theta Angle in degrees through which to rotate the camera
Definition at line 66 of file Camera.cpp.
References f, and m_ViewMatrix.
void Camera::rotateZ (GLfloat theta)
Rotate through the X-Y plane (`Z-axis`/`roll`)
Parameters
theta Angle in degrees through which to rotate the camera
Definition at line 71 of file Camera.cpp.
References f, and m_ViewMatrix.
void Camera::setOrthogonal (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ)
Set an orthogonal lens for the camera.
Parameters
width Width of the viewport
height Height of the viewport
nearZ Near-plane Z coordinate
farZ Far-plane Z coordinate
Definition at line 26 of file Camera.cpp.
References f, and m_ProjMatrix.
Referenced by Camera().
void Camera::setPerspective (GLuint width, GLuint height, GLfloat nearZ, GLfloat farZ, GLfloat fovy)
Set a perspective lens for the camera.
Parameters
width Width of the viewport
height Height of the viewport
nearZ Near-plane Z coordinate
farZ Far-plane Z coordinate
fovy Field-of-view, in degrees
Definition at line 36 of file Camera.cpp.
References h, m_ProjMatrix, and w.
Referenced by Camera().
Member Data Documentation
glm::mat4 Camera::m_ProjMatrix [private]
Current projection matrix state.
Definition at line 135 of file Camera.h.
Referenced by apply(), getProjectionMatrix(), setOrthogonal(), and setPerspective().
glm::mat4 Camera::m_ViewMatrix [private]
Current view matrix state.
Definition at line 134 of file Camera.h.
Referenced by apply(), getViewMatrix(), lookAt(), pan(), rotateX(), rotateY(), and rotateZ().
The documentation for this class was generated from the following files:
LunarDrift/engine/graphics/Camera.h
LunarDrift/engine/graphics/Camera.cpp