Model Class Reference
Container for and loader of `model data` (a combination of vertex and texture data)
#include <Model.h>
Classes
struct Vertex
Predefined vertex format for standard 3D models.
Public Member Functions
Model (Context *context, const std::string &path)
Constructor for loading a model from an OBJ file.
Model (Context *context, const std::vector< Vertex > &vertices)
Constructor for a model using predefined vertex list.
Model (Context *context, const std::vector< Vertex > &vertices, const std::vector< unsigned short > &indices)
Constructor for a model using predefined vertex and index lists.
~Model ()
Default destructor.
void draw (Context *context, std::shared_ptr< ShaderProgram > shader) const
Draw the model using a given shader.
void setPrimitiveMode (PrimitiveMode mode)
Set the typology of the model geometry for rendering.
void setVertexArrayObject (std::shared_ptr< VertexArrayObject > vao)
Associate a given vertex array object with the model.
std::weak_ptr< VertexArrayObject > getVertexArrayObject () const
Access associated vertex array object.
Private Member Functions
void transferToGPU (Context *context, const std::vector< Vertex > &vertices, const std::vector< unsigned short > *const indices=nullptr)
Compile model data into OpenGL objects for managing them GPU-side.
void getVertexAttributes (std::vector< VertexAttribute > *attribs) const
Fill a vector with vertex attributes to map the inputs to shaders.
Private Attributes
std::shared_ptr< VertexArrayObject > m_VAO
Associated vertex array object.
PrimitiveMode m_PrimitiveMode
Typology of the model geometry.
Detailed Description
Container for and loader of `model data` (a combination of vertex and texture data)
Precondition
A valid OpenGL context must be present to the program
Author
Hayley Hatton
Date
06/03/2016
See also
VertexBufferObject
ShaderProgram
Texture
VertexArrayObject
Definition at line 34 of file Model.h.
Constructor & Destructor Documentation
Model::Model (Context * context, const std::string & path)
Constructor for loading a model from an OBJ file.
Parameters
context Graphical context
path Path to the OBJ file to load model data from
Definition at line 7 of file Model.cpp.
References ModelLoader::compile(), ModelLoader::getNumVertices(), transferToGPU(), and Triangles.
Model::Model (Context * context, const std::vector< Vertex > & vertices)
Constructor for a model using predefined vertex list.
Parameters
context Graphical context
vertices List of vertices to make model from
Definition at line 33 of file Model.cpp.
References transferToGPU().
Model::Model (Context * context, const std::vector< Vertex > & vertices, const std::vector< unsigned short > & indices)
Constructor for a model using predefined vertex and index lists.
Parameters
context Graphical context
vertices List of vertices to make model from
indices List of indices to connect vertices with
Definition at line 39 of file Model.cpp.
References transferToGPU().
Model::~Model ()
Default destructor.
Definition at line 48 of file Model.cpp.
Member Function Documentation
void Model::draw (Context * context, std::shared_ptr< ShaderProgram > shader) const
Draw the model using a given shader.
Parameters
context Graphics context
shader Shader to draw the model with
Todo
Todo (Hayley#6#03/09/16): Handle different vertex connections
Definition at line 118 of file Model.cpp.
References getVertexArrayObject(), and m_PrimitiveMode.
std::weak_ptr< VertexArrayObject > Model::getVertexArrayObject () const
Access associated vertex array object.
Returns
Associated vertex array object
Definition at line 113 of file Model.cpp.
References m_VAO.
Referenced by draw().
void Model::getVertexAttributes (std::vector< VertexAttribute > * attribs) const [private]
Fill a vector with vertex attributes to map the inputs to shaders.
Parameters
Pointer to vector map of vertex attributes
Definition at line 80 of file Model.cpp.
References VertexAttribute::Float.
Referenced by transferToGPU().
void Model::setPrimitiveMode (PrimitiveMode mode) [inline]
Set the typology of the model geometry for rendering.
Parameters
mode Typology class
Definition at line 86 of file Model.h.
void Model::setVertexArrayObject (std::shared_ptr< VertexArrayObject > vao)
Associate a given vertex array object with the model.
Parameters
vao Vertex array object to associate with
Definition at line 108 of file Model.cpp.
References m_VAO.
Referenced by transferToGPU().
void Model::transferToGPU (Context * context, const std::vector< Vertex > & vertices, const std::vector< unsigned short > *const indices = nullptr) [private]
Compile model data into OpenGL objects for managing them GPU-side.
Parameters
context Graphical context
vertices Vector of model vertex data
indices Ptr to vector of model index data (optional)
Definition at line 54 of file Model.cpp.
References getVertexAttributes(), and setVertexArrayObject().
Referenced by Model().
Member Data Documentation
PrimitiveMode Model::m_PrimitiveMode [private]
Typology of the model geometry.
Definition at line 102 of file Model.h.
Referenced by draw().
std::shared_ptr<VertexArrayObject> Model::m_VAO [private]
Associated vertex array object.
Definition at line 101 of file Model.h.
Referenced by getVertexArrayObject(), and setVertexArrayObject().
The documentation for this class was generated from the following files:
LunarDrift/engine/containers/Model.h
LunarDrift/engine/containers/Model.cpp