SceneObject Class Reference
Abstract class for encapsulating self-management of scene entities.
#include <SceneObject.h>
Public Types
enum State { State::Ready,
State::Dying,
State::Dead
 }
Enumeration for scene object lifetime states.
Public Member Functions
SceneObject (Context *context)
Default constructor.
virtual ~SceneObject ()
Default destructor.
State getState () const
Retrieve the current lifetime stage the object is in.
void setDying ()
Set the scene object to begin the dying process.
bool addComponent (std::shared_ptr< SceneObjectComponent > component)
Add a component to the scene object.
std::shared_ptr< SceneObjectComponent > getComponent (const std::string &name)
Access a component attached to the scene object.
void setPosition (const glm::vec3 &pos)
Set the position of the entity within the scene.
const glm::vec3 & getPosition () const
Access the current position of the entity in the scene.
void setPitch (GLfloat angle)
Set the pitch angle of the entity (`X-Axis Rotation`)
GLfloat getPitch () const
Get the pitch angle of the entity (`X-Axis Rotation`)
void setYaw (GLfloat angle)
Set the yaw angle of the entity (`Y-Axis Rotation`)
GLfloat getYaw () const
Get the yaw angle of the entity (`Y-Axis Rotation`)
void setRoll (GLfloat angle)
Set the roll angle of the entity (`Z-Axis Rotation`)
GLfloat getRoll () const
Get the roll angle of the entity (`Z-Axis Rotation`)
void setRotations (const glm::vec3 &angles)
Set all the rotation states of the entity at once.
const glm::vec3 & getRotations () const
Get all the rotation states of the entity at once.
virtual void step (double dt)
Step the simulation state.
virtual void predraw (Context *context)
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
void updateModelMatrixState (Context *context, std::shared_ptr< ShaderProgram > shader) const
Use the standard position and rotation states as a model matrix This constructs a model matrix representing the position and rotation state, and tries to upload it into the u_ModelMatrix uniform in the presented shader, taking away the effort of doing this on every object from the programmers.
virtual void draw (Context *context, std::shared_ptr< ShaderManager > shaders)=0
Draw the object in its current state.
Private Attributes
std::map< std::string, std::shared_ptr< SceneObjectComponent > > m_Components
glm::vec3 m_Position
glm::vec3 m_Rotation
State m_State
Current life-stage state.
Detailed Description
Abstract class for encapsulating self-management of scene entities.
Precondition
A valid OpenGL context must be present to the program
Author
Hayley Hatton
Date
06/03/2016
Definition at line 14 of file SceneObject.h.
Member Enumeration Documentation
enum SceneObject::State [strong]
Enumeration for scene object lifetime states.
Enumerator
Ready
 Loaded and ready for use.
Dying
 Loaded, but marked as dead and needing cleanup.
Dead
 Cleaned up and finished; pending dtor.
Definition at line 28 of file SceneObject.h.
Constructor & Destructor Documentation
SceneObject::SceneObject (Context * context)
Default constructor.
Parameters
context Graphics context
Definition at line 6 of file SceneObject.cpp.
SceneObject::~SceneObject () [virtual]
Default destructor.
Definition at line 12 of file SceneObject.cpp.
Member Function Documentation
bool SceneObject::addComponent (std::shared_ptr< SceneObjectComponent > component)
Add a component to the scene object.
Parameters
component Smart pointer to the component
Returns
True if added; false if already exists
Definition at line 18 of file SceneObject.cpp.
References m_Components.
Referenced by setDying(), and TestTriangle::TestTriangle().
virtual void SceneObject::draw (Context * context, std::shared_ptr< ShaderManager > shaders) [pure virtual]
Draw the object in its current state.
Parameters
context Graphics context
shaders Shader manager containing shader programs for use
Implemented in TestTriangle.
Referenced by getRotations().
std::shared_ptr< SceneObjectComponent > SceneObject::getComponent (const std::string & name)
Access a component attached to the scene object.
Parameters
name Identifying name of the component type
Returns
Smart pointer to the component; nullptr if none of that type
Definition at line 30 of file SceneObject.cpp.
References m_Components.
Referenced by setDying().
GLfloat SceneObject::getPitch () const [inline]
Get the pitch angle of the entity (`X-Axis Rotation`)
Returns
Current pitch angle
Definition at line 80 of file SceneObject.h.
References m_Rotation.
const glm::vec3& SceneObject::getPosition () const [inline]
Access the current position of the entity in the scene.
Returns
Current position
Definition at line 68 of file SceneObject.h.
References m_Position.
GLfloat SceneObject::getRoll () const [inline]
Get the roll angle of the entity (`Z-Axis Rotation`)
Returns
Current roll angle
Definition at line 104 of file SceneObject.h.
References m_Rotation.
const glm::vec3& SceneObject::getRotations () const [inline]
Get all the rotation states of the entity at once.
Returns
Current rotation angles as a vector
Definition at line 116 of file SceneObject.h.
References draw(), m_Rotation, predraw(), step(), and updateModelMatrixState().
State SceneObject::getState () const [inline]
Retrieve the current lifetime stage the object is in.
Returns
Current life-stage state
Definition at line 39 of file SceneObject.h.
References m_State.
GLfloat SceneObject::getYaw () const [inline]
Get the yaw angle of the entity (`Y-Axis Rotation`)
Returns
Current yaw angle
Definition at line 92 of file SceneObject.h.
References m_Rotation.
void SceneObject::predraw (Context * context) [virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Reimplemented in TestTriangle.
Definition at line 45 of file SceneObject.cpp.
References m_Components.
Referenced by getRotations(), and TestTriangle::predraw().
void SceneObject::setDying () [inline]
Set the scene object to begin the dying process.
Definition at line 42 of file SceneObject.h.
References addComponent(), Dying, getComponent(), and m_State.
Referenced by TestTriangle::onMessage().
void SceneObject::setPitch (GLfloat angle) [inline]
Set the pitch angle of the entity (`X-Axis Rotation`)
Parameters
angle New pitch angle
Definition at line 74 of file SceneObject.h.
References m_Rotation.
void SceneObject::setPosition (const glm::vec3 & pos) [inline]
Set the position of the entity within the scene.
Parameters
pos New position
Definition at line 62 of file SceneObject.h.
References m_Position.
void SceneObject::setRoll (GLfloat angle) [inline]
Set the roll angle of the entity (`Z-Axis Rotation`)
Parameters
angle New roll angle
Definition at line 98 of file SceneObject.h.
References m_Rotation.
void SceneObject::setRotations (const glm::vec3 & angles) [inline]
Set all the rotation states of the entity at once.
Parameters
angles New rotation angles as a vector
Definition at line 110 of file SceneObject.h.
References m_Rotation.
void SceneObject::setYaw (GLfloat angle) [inline]
Set the yaw angle of the entity (`Y-Axis Rotation`)
Parameters
angle New yaw angle
Definition at line 86 of file SceneObject.h.
References m_Rotation.
void SceneObject::step (double dt) [virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Reimplemented in TestTriangle.
Definition at line 39 of file SceneObject.cpp.
References m_Components.
Referenced by getRotations(), and TestTriangle::step().
void SceneObject::updateModelMatrixState (Context * context, std::shared_ptr< ShaderProgram > shader) const
Use the standard position and rotation states as a model matrix This constructs a model matrix representing the position and rotation state, and tries to upload it into the u_ModelMatrix uniform in the presented shader, taking away the effort of doing this on every object from the programmers.
Parameters
context Graphics context
shader Shader program to upload model matrix to
Definition at line 51 of file SceneObject.cpp.
References m_Position, and m_Rotation.
Referenced by getRotations().
Member Data Documentation
std::map<std::string, std::shared_ptr<SceneObjectComponent> > SceneObject::m_Components [private]
Definition at line 155 of file SceneObject.h.
Referenced by addComponent(), getComponent(), predraw(), and step().
glm::vec3 SceneObject::m_Position [private]
Definition at line 156 of file SceneObject.h.
Referenced by getPosition(), setPosition(), and updateModelMatrixState().
glm::vec3 SceneObject::m_Rotation [private]
Definition at line 157 of file SceneObject.h.
Referenced by getPitch(), getRoll(), getRotations(), getYaw(), setPitch(), setRoll(), setRotations(), setYaw(), and updateModelMatrixState().
State SceneObject::m_State [private]
Current life-stage state.
Definition at line 158 of file SceneObject.h.
Referenced by getState(), and setDying().
The documentation for this class was generated from the following files:
LunarDrift/engine/containers/SceneObject.h
LunarDrift/engine/containers/SceneObject.cpp