ShaderProgram Class Reference
Container for a GLSL shader program and its constituent shaders.
#include <ShaderProgram.h>
Public Member Functions
ShaderProgram (const std::string &vertex, const std::string &fragment)
Normal shader program constructor.
ShaderProgram (const std::string &vertex, const std::string &geometry, const std::string &fragment)
Shader program w/ geometry shader constructor.
virtual ~ShaderProgram ()
Default destructor.
void load (const std::string &vertex, const std::string &fragment)
Loads a shader program (OpenGL 2 required)
void load (const std::string &vertex, const std::string &geometry, const std::string &fragment)
Loads a shader program (OpenGL 3.2 required)
void unload ()
Unloads the shader program and its children.
GLuint getProgramHandle () const
Returns the program handle of the shader program.
GLint getAttributeLocation (const std::string &name) const
Obtains the location of an attribute in the shader program.
GLint getUniformLocation (const std::string &name) const
Obtains the location of a uniform in the shader program.
int getUniformBlockLocation (const std::string &name) const
Get the identifier of a given uniform block.
void bindUniformBlock (const std::string &name, int bindingPoint) const
Bind a given uniform block at an index.
void use (Context *context)
Bind the shader program to the OpenGL state pipeline.
Protected Member Functions
GLint loadAndCompileFile (const std::string &name, GLenum stage)
Load and compile shader code from a file.
void readShaderFile (const std::string &filename, std::string *data)
Reads a shader from a file and returns its source code.
Private Attributes
GLuint m_ProgramHandle
Shader handlers.
GLint m_VertexShaderHandle
GLint m_GeometryShaderHandle
GLint m_FragmentShaderHandle
Detailed Description
Container for a GLSL shader program and its constituent shaders.
This is composed of two to three shaders (if using geometry shaders) compiled and linked into a `shader program`.
This supports Vertex/Fragment Shaders and Vertex/Geometry/Fragment Shaders. Version 4 is not supported, and so Tessellation Control and Evaluator shaders are available.
Precondition
A valid OpenGL context must be present to the program.
Author
Hayley Hatton
Date
06/03/2016
Definition at line 20 of file ShaderProgram.h.
Constructor & Destructor Documentation
ShaderProgram::ShaderProgram (const std::string & vertex, const std::string & fragment)
Normal shader program constructor.
Parameters
vertex Vertex shader filename, minus .vert extension
fragment Fragment shader filename, minus .frag extension
Exceptions
FileIOException
ShaderCompileException
OpenGLException
Definition at line 9 of file ShaderProgram.cpp.
References load().
ShaderProgram::ShaderProgram (const std::string & vertex, const std::string & geometry, const std::string & fragment)
Shader program w/ geometry shader constructor.
Parameters
vertex Vertex shader filename, minus .vert extension
geometry Geometry shader filename
fragment Fragment shader filename, minus .frag extension
Exceptions
FileIOException
ShaderCompileException
OpenGLException
Definition at line 16 of file ShaderProgram.cpp.
References load().
ShaderProgram::~ShaderProgram () [virtual]
Default destructor.
Definition at line 24 of file ShaderProgram.cpp.
References unload().
Member Function Documentation
void ShaderProgram::bindUniformBlock (const std::string & name, int bindingPoint) const [inline]
Bind a given uniform block at an index.
Parameters
name Name of the uniform block
Returns
Index to bind the uniform block at
Definition at line 123 of file ShaderProgram.h.
References m_ProgramHandle.
GLint ShaderProgram::getAttributeLocation (const std::string & name) const [inline]
Obtains the location of an attribute in the shader program.
Parameters
name Name of the attribute
Returns
Handle to the attribute; -1 if error
Definition at line 96 of file ShaderProgram.h.
References m_ProgramHandle.
GLuint ShaderProgram::getProgramHandle () const [inline]
Returns the program handle of the shader program.
Returns
Program handle
Definition at line 89 of file ShaderProgram.h.
References m_ProgramHandle.
int ShaderProgram::getUniformBlockLocation (const std::string & name) const [inline]
Get the identifier of a given uniform block.
Parameters
name Name of the uniform block
Returns
Identifier of the uniform block
Definition at line 114 of file ShaderProgram.h.
References m_ProgramHandle.
GLint ShaderProgram::getUniformLocation (const std::string & name) const [inline]
Obtains the location of a uniform in the shader program.
Parameters
name Name of the uniform
Returns
Handle to the uniform; -1 if error
Definition at line 105 of file ShaderProgram.h.
References m_ProgramHandle.
Referenced by Camera::apply().
void ShaderProgram::load (const std::string & vertex, const std::string & fragment)
Loads a shader program (OpenGL 2 required)
Parameters
vertex Vertex shader filename, minus .vert extension
fragment Fragment shader filename, minus .frag extension
Exceptions
FileIOException
ShaderCompileException
OpenGLException
Definition at line 29 of file ShaderProgram.cpp.
References loadAndCompileFile(), m_FragmentShaderHandle, m_GeometryShaderHandle, m_ProgramHandle, and m_VertexShaderHandle.
Referenced by ShaderProgram().
void ShaderProgram::load (const std::string & vertex, const std::string & geometry, const std::string & fragment)
Loads a shader program (OpenGL 3.2 required)
Parameters
vertex Vertex shader filename, minus .vert extension
geometry Geometry shader filename, minus .geom extension
fragment Fragment shader filename, minus .frag extension
Exceptions
FileIOException
ShaderCompileException
OpenGLException
Definition at line 73 of file ShaderProgram.cpp.
References loadAndCompileFile(), m_FragmentShaderHandle, m_GeometryShaderHandle, m_ProgramHandle, and m_VertexShaderHandle.
GLint ShaderProgram::loadAndCompileFile (const std::string & name, GLenum stage) [protected]
Load and compile shader code from a file.
Parameters
name Shader filename
stage Shader stage (e.g. GL_VERTEX_SHADER)
Returns
Handle to the shader code on the GPU
Exceptions
FileIOException
ShaderCompileException
Definition at line 121 of file ShaderProgram.cpp.
References readShaderFile().
Referenced by load(), and use().
void ShaderProgram::readShaderFile (const std::string & filename, std::string * data) [protected]
Reads a shader from a file and returns its source code.
Parameters
filename Location of the shader file
data Ptr to string to be filled with the shader file's data
Exceptions
FileIOException
Definition at line 183 of file ShaderProgram.cpp.
References Config::get().
Referenced by loadAndCompileFile(), and use().
void ShaderProgram::unload ()
Unloads the shader program and its children.
Definition at line 174 of file ShaderProgram.cpp.
References m_FragmentShaderHandle, m_GeometryShaderHandle, m_ProgramHandle, and m_VertexShaderHandle.
Referenced by ~ShaderProgram().
void ShaderProgram::use (Context * context) [inline]
Bind the shader program to the OpenGL state pipeline.
Definition at line 131 of file ShaderProgram.h.
References loadAndCompileFile(), m_ProgramHandle, and readShaderFile().
Referenced by Camera::apply().
Member Data Documentation
GLint ShaderProgram::m_FragmentShaderHandle [private]
Definition at line 159 of file ShaderProgram.h.
Referenced by load(), and unload().
GLint ShaderProgram::m_GeometryShaderHandle [private]
Definition at line 158 of file ShaderProgram.h.
Referenced by load(), and unload().
GLuint ShaderProgram::m_ProgramHandle [private]
Shader handlers.
Definition at line 156 of file ShaderProgram.h.
Referenced by bindUniformBlock(), getAttributeLocation(), getProgramHandle(), getUniformBlockLocation(), getUniformLocation(), load(), unload(), and use().
GLint ShaderProgram::m_VertexShaderHandle [private]
Definition at line 157 of file ShaderProgram.h.
Referenced by load(), and unload().
The documentation for this class was generated from the following files:
LunarDrift/engine/graphics/shaders/ShaderProgram.h
LunarDrift/engine/graphics/shaders/ShaderProgram.cpp