Program Class Reference
Top-level program entry point class.
#include <Program.h>
Public Member Functions
Program (const std::string &name, Context *context)
Object-oriented entry point to the program.
virtual ~Program ()
Default destructor.
const std::string & getName () const
Access the name of the program.
virtual void step (double dt)
Called on the stepping of the simulation state.
virtual void frame (Context *context)
Called on the rendering of a frame.
Protected Member Functions
void setRenderer (Context *context, std::shared_ptr< Renderer > renderer)
Set the active renderer to render the scenes with.
virtual std::shared_ptr< Renderer > getRenderer (Context *context) const =0
Retrieve a new renderer for a given stereo mode from the subclass.
void setActiveScene (std::shared_ptr< Scene > scene)
Set the active scene to manage and render.
Private Attributes
const std::string m_Name
Name of the program.
std::shared_ptr< Renderer > m_Renderer
Active renderer.
std::shared_ptr< Scene > m_ActiveScene
Active scene.
Detailed Description
Top-level program entry point class.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 14 of file Program.h.
Constructor & Destructor Documentation
Program::Program (const std::string & name, Context * context)
Object-oriented entry point to the program.
Parameters
name String name of the program
context Graphics context
Definition at line 5 of file Program.cpp.
Program::~Program () [virtual]
Default destructor.
Definition at line 12 of file Program.cpp.
Member Function Documentation
void Program::frame (Context * context) [virtual]
Called on the rendering of a frame.
Parameters
context Graphical context
Reimplemented in LunarDriftProgram.
Definition at line 23 of file Program.cpp.
References getRenderer(), m_ActiveScene, m_Renderer, and setRenderer().
Referenced by LunarDriftProgram::frame(), getName(), and WindowPC::renderingThread().
const std::string& Program::getName () const [inline]
Access the name of the program.
Returns
Reference to name. Do not keep the reference; copy instead
Definition at line 32 of file Program.h.
References frame(), getRenderer(), m_Name, setActiveScene(), setRenderer(), and step().
virtual std::shared_ptr<Renderer> Program::getRenderer (Context * context) const [protected], [pure virtual]
Retrieve a new renderer for a given stereo mode from the subclass.
Parameters
context Graphics context
mode Type of stereo renderer requested by the system
Returns
Smart pointer to the new appropriate renderer
Implemented in LunarDriftProgram.
Referenced by frame(), and getName().
void Program::setActiveScene (std::shared_ptr< Scene > scene) [protected]
Set the active scene to manage and render.
Parameters
scene Active scene
Definition at line 43 of file Program.cpp.
References m_ActiveScene.
Referenced by getName(), and LunarDriftProgram::LunarDriftProgram().
void Program::setRenderer (Context * context, std::shared_ptr< Renderer > renderer) [protected]
Set the active renderer to render the scenes with.
Parameters
context Graphics context
renderer Renderer to draw with
Definition at line 36 of file Program.cpp.
References m_Renderer.
Referenced by frame(), and getName().
void Program::step (double dt) [virtual]
Called on the stepping of the simulation state.
Parameters
dt Delta time, in seconds
Reimplemented in LunarDriftProgram.
Definition at line 17 of file Program.cpp.
References m_ActiveScene.
Referenced by getName(), WindowPC::simulationThread(), and LunarDriftProgram::step().
Member Data Documentation
std::shared_ptr<Scene> Program::m_ActiveScene [private]
Active scene.
Definition at line 72 of file Program.h.
Referenced by frame(), setActiveScene(), and step().
const std::string Program::m_Name [private]
Name of the program.
Definition at line 70 of file Program.h.
Referenced by getName().
std::shared_ptr<Renderer> Program::m_Renderer [private]
Active renderer.
Definition at line 71 of file Program.h.
Referenced by frame(), and setRenderer().
The documentation for this class was generated from the following files:
LunarDrift/engine/Program.h
LunarDrift/engine/Program.cpp