SceneObjectComponent Class Reference
Base class for components that are to be attached to scene objects.
#include <SceneObjectComponent.h>
Public Member Functions
SceneObjectComponent (const std::string &name, SceneObject *parent, std::weak_ptr< MetaManager > managers)
Default constructor.
virtual ~SceneObjectComponent ()
Default destructor.
virtual void step (double dt)=0
Step the simulation state.
virtual void predraw (Context *context)=0
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
SceneObject * getParent ()
Access the parent class that owns this component.
std::weak_ptr< MetaManager > getMetaManager ()
Access the metamanager for the scene that the parent is a part of.
Protected Attributes
std::weak_ptr< MetaManager > m_Managers
Scene's managers.
Private Attributes
SceneObject * m_Parent
Class that has ownership of this component.
Detailed Description
Base class for components that are to be attached to scene objects.
Author
Hayley Hatton
Date
06/03/2016
Definition at line 15 of file SceneObjectComponent.h.
Constructor & Destructor Documentation
SceneObjectComponent::SceneObjectComponent (const std::string & name, SceneObject * parent, std::weak_ptr< MetaManager > managers)
Default constructor.
Parameters
name Identifying name of the component class
parent Pointer to the scene object to attach component to
managers Metamanager for accessing scene's managers
Definition at line 5 of file SceneObjectComponent.cpp.
SceneObjectComponent::~SceneObjectComponent () [virtual]
Default destructor.
Definition at line 16 of file SceneObjectComponent.cpp.
Member Function Documentation
std::weak_ptr<MetaManager> SceneObjectComponent::getMetaManager () [inline]
Access the metamanager for the scene that the parent is a part of.
Returns
Weakly-referenced pointer to the owning scene's metamanager
Definition at line 57 of file SceneObjectComponent.h.
References m_Managers.
SceneObject* SceneObjectComponent::getParent () [inline]
Access the parent class that owns this component.
Returns
Reference to the parent class
Definition at line 51 of file SceneObjectComponent.h.
References m_Parent.
Referenced by CollisionComponent::CollisionComponent(), HitpointComponent::onMessage(), LifeTimeComponent::step(), and CollisionComponent::~CollisionComponent().
virtual void SceneObjectComponent::predraw (Context * context) [pure virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Implemented in CollisionComponent, LifeTimeComponent, and HitpointComponent.
virtual void SceneObjectComponent::step (double dt) [pure virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Implemented in CollisionComponent, LifeTimeComponent, and HitpointComponent.
Member Data Documentation
std::weak_ptr<MetaManager> SceneObjectComponent::m_Managers [protected]
Scene's managers.
Definition at line 60 of file SceneObjectComponent.h.
Referenced by getMetaManager(), and CollisionComponent::~CollisionComponent().
SceneObject* SceneObjectComponent::m_Parent [private]
Class that has ownership of this component.
Definition at line 63 of file SceneObjectComponent.h.
Referenced by getParent().
The documentation for this class was generated from the following files:
LunarDrift/engine/components/SceneObjectComponent.h
LunarDrift/engine/components/SceneObjectComponent.cpp