InputMap Class Reference
#include <InputMap.h>
Public Member Functions
Keyboard * getKeyboard ()
Static Public Member Functions
static InputMap & getInstance ()
Private Member Functions
InputMap ()
InputMap (InputMap const &)=delete
void operator= (InputMap const &)=delete
Private Attributes
Keyboard m_Keyboard
Detailed Description
Definition at line 5 of file InputMap.h.
Constructor & Destructor Documentation
InputMap::InputMap () [inline], [private]
Definition at line 24 of file InputMap.h.
References operator=().
InputMap::InputMap (InputMap const &) [private], [delete]
Member Function Documentation
static InputMap& InputMap::getInstance () [inline], [static]
Definition at line 8 of file InputMap.h.
Referenced by WindowPC::handleWin32EventQueue(), LunarDriftProgram::LunarDriftProgram(), and TestScene3D::step().
Keyboard* InputMap::getKeyboard () [inline]
Definition at line 14 of file InputMap.h.
References m_Keyboard.
Referenced by WindowPC::handleWin32EventQueue(), LunarDriftProgram::LunarDriftProgram(), and TestScene3D::step().
void InputMap::operator= (InputMap const &) [private], [delete]
Referenced by InputMap().
Member Data Documentation
Keyboard InputMap::m_Keyboard [private]
Definition at line 20 of file InputMap.h.
Referenced by getKeyboard().
The documentation for this class was generated from the following file:
LunarDrift/engine/input/InputMap.h