TestScene3D Class Reference
#include <TestScene3D.h>
Public Member Functions
TestScene3D (Context *context)
Default constructor.
virtual ~TestScene3D ()
Default destructor.
void setSize (GLsizei width, GLsizei height) override
Called to update scene elements with the viewport information.
void step (double dt) override
Step the scene's simulation state.
void predraw (Context *context) override
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
void onMessage (std::shared_ptr< Message > event) override
Called when a subscribed event is raised.
Private Attributes
GLfloat m_Distance
GLfloat m_Offset
Additional Inherited Members
Detailed Description
Definition at line 6 of file TestScene3D.h.
Constructor & Destructor Documentation
TestScene3D::TestScene3D (Context * context)
Default constructor.
Parameters
context Graphics context
Definition at line 8 of file TestScene3D.cpp.
References Scene::addObject(), f, Config::get(), Context::getDimensions(), Config::getFloat(), MessageSystem::getInstance(), Scene::getManagers(), m_Distance, Scene::setActiveCamera(), and MessageSystem::subscribe().
TestScene3D::~TestScene3D () [virtual]
Default destructor.
Definition at line 32 of file TestScene3D.cpp.
Member Function Documentation
void TestScene3D::onMessage (std::shared_ptr< Message > event) [override], [virtual]
Called when a subscribed event is raised.
Parameters
event Smart pointer to the raised event object
Implements IMessageListener.
Definition at line 75 of file TestScene3D.cpp.
void TestScene3D::predraw (Context * context) [override], [virtual]
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Reimplemented from Scene.
Definition at line 70 of file TestScene3D.cpp.
References Scene::predraw().
void TestScene3D::setSize (GLsizei width, GLsizei height) [override], [virtual]
Called to update scene elements with the viewport information.
Parameters
width Width of the viewport in pixels
height Height of the viewport in pixels
Reimplemented from Scene.
Definition at line 38 of file TestScene3D.cpp.
References Config::get(), Scene::getActiveCamera(), and Config::getFloat().
void TestScene3D::step (double dt) [override], [virtual]
Step the scene's simulation state.
Parameters
dt Delta-time since last step call in seconds
Reimplemented from Scene.
Definition at line 48 of file TestScene3D.cpp.
References f, Scene::getActiveCamera(), InputMap::getInstance(), InputMap::getKeyboard(), Keyboard::isKeyDown(), m_Distance, m_Offset, and Scene::step().
Member Data Documentation
GLfloat TestScene3D::m_Distance [private]
Definition at line 50 of file TestScene3D.h.
Referenced by step(), and TestScene3D().
GLfloat TestScene3D::m_Offset [private]
Definition at line 50 of file TestScene3D.h.
Referenced by step().
The documentation for this class was generated from the following files:
LunarDrift/game/scenes/alphaspace/TestScene3D.h
LunarDrift/game/scenes/alphaspace/TestScene3D.cpp