FileIOException Class Reference
Exception raised whenever a core filesystem operation fails.
#include <FileIOException.h>
Public Member Functions
FileIOException (const std::string &file, const std::string &err)
Default constructor.
const std::string & getFile () const
const std::string & getError () const
Private Attributes
const std::string m_File
const std::string m_Error
Detailed Description
Exception raised whenever a core filesystem operation fails.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 12 of file FileIOException.h.
Constructor & Destructor Documentation
FileIOException::FileIOException (const std::string & file, const std::string & err)
Default constructor.
Parameters
file File name of the failed file.
err Error string
Definition at line 3 of file FileIOException.cpp.
Member Function Documentation
const std::string& FileIOException::getError () const [inline]
Definition at line 26 of file FileIOException.h.
References m_Error.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& FileIOException::getFile () const [inline]
Definition at line 24 of file FileIOException.h.
References m_File.
Referenced by WindowPC::renderingThread(), and WinMain().
Member Data Documentation
const std::string FileIOException::m_Error [private]
Definition at line 30 of file FileIOException.h.
Referenced by getError().
const std::string FileIOException::m_File [private]
Definition at line 29 of file FileIOException.h.
Referenced by getFile().
The documentation for this class was generated from the following files:
LunarDrift/engine/exceptions/FileIOException.h
LunarDrift/engine/exceptions/FileIOException.cpp