LunarDriftProgram Class Reference
Top-level program class for our game.
#include <LunarDriftProgram.h>
Public Member Functions
LunarDriftProgram (Context *context)
Object-oriented entry point to the program.
~LunarDriftProgram ()
Default destructor.
void step (double dt) override
Called on the stepping of the simulation state.
void frame (Context *context) override
Called on the rendering of a frame.
void onMessage (std::shared_ptr< Message > event) override
Called when a subscribed event is raised.
Static Public Attributes
static const std::string ms_Name = `Perpendicular`
Name of the program.
Protected Member Functions
std::shared_ptr< Renderer > getRenderer (Context *context) const override
Retrieve a new renderer for a given stereo mode from the subclass.
Detailed Description
Top-level program class for our game.
Author
Hayley Hatton
Date
17/03/2016
Definition at line 12 of file LunarDriftProgram.h.
Constructor & Destructor Documentation
LunarDriftProgram::LunarDriftProgram (Context * context)
Object-oriented entry point to the program.
Parameters
context Graphics context
Definition at line 10 of file LunarDriftProgram.cpp.
References Config::get(), InputMap::getInstance(), InputMap::getKeyboard(), Config::load(), Keyboard::mapKeyToInput(), Config::set(), and Program::setActiveScene().
LunarDriftProgram::~LunarDriftProgram ()
Default destructor.
Definition at line 24 of file LunarDriftProgram.cpp.
Member Function Documentation
void LunarDriftProgram::frame (Context * context) [override], [virtual]
Called on the rendering of a frame.
Parameters
context Graphical context
Reimplemented from Program.
Definition at line 35 of file LunarDriftProgram.cpp.
References Program::frame().
std::shared_ptr< Renderer > LunarDriftProgram::getRenderer (Context * context) const [override], [protected], [virtual]
Retrieve a new renderer for a given stereo mode from the subclass.
Returns
Smart pointer to the new appropriate renderer
Implements Program.
Definition at line 47 of file LunarDriftProgram.cpp.
References Context::getDimensions(), h, and w.
void LunarDriftProgram::onMessage (std::shared_ptr< Message > event) [override], [virtual]
Called when a subscribed event is raised.
Parameters
event Smart pointer to the raised event object
Implements IMessageListener.
Definition at line 43 of file LunarDriftProgram.cpp.
void LunarDriftProgram::step (double dt) [override], [virtual]
Called on the stepping of the simulation state.
Parameters
dt Delta time, in seconds
Reimplemented from Program.
Definition at line 30 of file LunarDriftProgram.cpp.
References Program::step().
Member Data Documentation
const std::string LunarDriftProgram::ms_Name = `Perpendicular` [static]
Name of the program.
Definition at line 45 of file LunarDriftProgram.h.
Referenced by WinMain().
The documentation for this class was generated from the following files:
LunarDrift/game/LunarDriftProgram.h
LunarDrift/game/LunarDriftProgram.cpp