ModelLoader Class Reference
Loads a Wavefront Object file and allows the model to be modified.
#include <ModelLoader.h>
Classes
struct Vertex
Public Member Functions
ModelLoader ()
Default constructor.
ModelLoader (const std::string &path)
Load model from path.
virtual ~ModelLoader ()
Default destructor.
void load (const std::string &path)
Load model from path.
int getNumVertices () const
Return the number of vertices loaded.
bool compile (int stride, int positionOffset, int normalOffset, int texOffset, int colorOffset, int *elements, void **output) const
Compile the loaded model into a custom interleaved structure.
Private Member Functions
void loadMaterials (std::map< std::string, glm::vec3 > &buffer, const std::string &filepath) const
Load the color information from an external material file.
Private Attributes
std::map< std::string, std::vector< Vertex > > m_VertexGroups
Detailed Description
Loads a Wavefront Object file and allows the model to be modified.
Wavefront Object Files are free, license-free, text-based model-storing file format.
Author
Hayley Hatton
Date
06/03/2016
See also
Model
Definition at line 19 of file ModelLoader.h.
Constructor & Destructor Documentation
ModelLoader::ModelLoader () [inline]
Default constructor.
Definition at line 23 of file ModelLoader.h.
References compile(), getNumVertices(), load(), and ~ModelLoader().
ModelLoader::ModelLoader (const std::string & path)
Load model from path.
Parameters
path Location of model file.
Definition at line 10 of file ModelLoader.cpp.
References load().
ModelLoader::~ModelLoader () [virtual]
Default destructor.
Definition at line 15 of file ModelLoader.cpp.
Referenced by ModelLoader().
Member Function Documentation
bool ModelLoader::compile (int stride, int positionOffset, int normalOffset, int texOffset, int colorOffset, int * elements, void ** output) const
Compile the loaded model into a custom interleaved structure.
Parameters
stride The size of the structure
positionOffset The offset to the position vector in the structure
normalOffset The offset to the normal vector in the structure
texOffset The offset to the texture coordinates in the structure
colorOffset The offset to the color vectors in the structure
elements Pointer to the number of elements loaded
output Pointer to store a pointer to the compiled data
Returns
Error status. True if success, false if fail
Definition at line 148 of file ModelLoader.cpp.
References ModelLoader::Vertex::color, g, getNumVertices(), i, m_VertexGroups, ModelLoader::Vertex::normal, ModelLoader::Vertex::position, and ModelLoader::Vertex::texCoord.
Referenced by Model::Model(), and ModelLoader().
int ModelLoader::getNumVertices () const
Return the number of vertices loaded.
Definition at line 137 of file ModelLoader.cpp.
References m_VertexGroups.
Referenced by compile(), Model::Model(), and ModelLoader().
void ModelLoader::load (const std::string & path)
Load model from path.
Parameters
path Location of model file.
Definition at line 21 of file ModelLoader.cpp.
References ModelLoader::Vertex::color, i, j, loadMaterials(), m_VertexGroups, modelPath, ModelLoader::Vertex::normal, ModelLoader::Vertex::position, and ModelLoader::Vertex::texCoord.
Referenced by ModelLoader().
void ModelLoader::loadMaterials (std::map< std::string, glm::vec3 > & buffer, const std::string & filepath) const [private]
Load the color information from an external material file.
Parameters
buffer Reference to map to store the material information.
filepath Location of material file.
Definition at line 198 of file ModelLoader.cpp.
Referenced by load().
Member Data Documentation
std::map<std::string, std::vector<Vertex> > ModelLoader::m_VertexGroups [private]
Definition at line 72 of file ModelLoader.h.
Referenced by compile(), getNumVertices(), and load().
The documentation for this class was generated from the following files:
LunarDrift/engine/containers/ModelLoader.h
LunarDrift/engine/containers/ModelLoader.cpp