Config Class Reference
A singleton that aggregates and encaspsulates access to config files.
#include <Config.h>
Public Member Functions
void load (const std::string &file)
Load an INI file into the configuration settings database.
void save (const std::string &file)
Save to an INI file from the configuration settings database.
void saveAll ()
Save all loaded configuration files with current settings.
const std::string & get (const std::string &file, const std::string &name) const
Access a setting from a loaded configuration file.
int getInt (const std::string &file, const std::string &name) const
Access a setting from a loaded configuration file.
bool getBool (const std::string &file, const std::string &name, bool unknownIsFalse=true) const
Access a setting from a loaded configuration file.
double getDouble (const std::string &file, const std::string &name) const
Access a setting from a loaded configuration file.
float getFloat (const std::string &file, const std::string &name) const
Access a setting from a loaded configuration file.
void set (const std::string &file, const std::string &name, const std::string value)
Set a setting in the configuration database.
void set (const std::string &file, const std::string &name, int value)
Set a setting in the configuration database.
void set (const std::string &file, const std::string &name, bool value)
Set a setting in the configuration database.
void set (const std::string &file, const std::string &name, double value)
Set a setting in the configuration database.
Static Public Member Functions
static Config & get ()
Access the singleton instance.
Private Member Functions
Config ()
Config (Config const &)
void operator= (Config const &)
Private Attributes
std::map< std::string, std::map< std::string, std::string > > m_FileData
Settings database.
Detailed Description
A singleton that aggregates and encaspsulates access to config files.
Most projects utilize .INI files to configure the program. They provide convenient storage places for configuration variables, and are both easily readable and modifiable by users from outside of the program. This singleton class allows these INI files to be conveniently handled and interfaced for easier use by programmers.
Note
`_engine` file is a virtual file for representing internal engine configuration states
Author
Hayley Hatton
Date
20/02/2016
Todo
Todo (Hayley#3#20/02/16): Directory control.
(Hayley#2#20/02/16): Access via [] operators?
Definition at line 22 of file Config.h.
Constructor & Destructor Documentation
Config::Config () [inline], [private]
Definition at line 160 of file Config.h.
References operator=().
Config::Config (Config const &) [private]
Member Function Documentation
static Config& Config::get () [inline], [static]
Access the singleton instance.
Returns
The actual Config instance.
Definition at line 29 of file Config.h.
References getBool(), getDouble(), getFloat(), getInt(), load(), save(), and saveAll().
Referenced by LunarDriftProgram::LunarDriftProgram(), ShaderProgram::readShaderFile(), TestScene3D::setSize(), and TestScene3D::TestScene3D().
const std::string & Config::get (const std::string & file, const std::string & name) const
Access a setting from a loaded configuration file.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to query.
Returns
String value associated with the queried setting.
Exceptions
ConfigurationException
Definition at line 124 of file Config.cpp.
References m_FileData.
bool Config::getBool (const std::string & file, const std::string & name, bool unknownIsFalse = true) const
Access a setting from a loaded configuration file.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to query.
Returns
True/false value associated with the queried setting.
Exceptions
ConfigurationException
Definition at line 163 of file Config.cpp.
Referenced by get().
double Config::getDouble (const std::string & file, const std::string & name) const
Access a setting from a loaded configuration file.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to query.
Returns
Double-precision decimal associated with the queried setting.
Exceptions
ConfigurationException
Definition at line 194 of file Config.cpp.
Referenced by get().
float Config::getFloat (const std::string & file, const std::string & name) const
Access a setting from a loaded configuration file.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to query.
Returns
Floating-point decimal associated with the queried setting.
Exceptions
ConfigurationException
Definition at line 211 of file Config.cpp.
Referenced by get(), TestScene3D::setSize(), and TestScene3D::TestScene3D().
int Config::getInt (const std::string & file, const std::string & name) const
Access a setting from a loaded configuration file.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to query.
Returns
Signed integer associated with the queried setting.
Exceptions
ConfigurationException
Definition at line 146 of file Config.cpp.
Referenced by get().
void Config::load (const std::string & file)
Load an INI file into the configuration settings database.
Parameters
file Name of the INI file, without the .ini extension.
Exceptions
FileIOException
Definition at line 27 of file Config.cpp.
References m_FileData, and trim().
Referenced by get(), and LunarDriftProgram::LunarDriftProgram().
void Config::operator= (Config const &) [private]
Referenced by Config().
void Config::save (const std::string & file)
Save to an INI file from the configuration settings database.
Parameters
file Name of the INI file, without the .ini extension.
Exceptions
FileIOException
Todo
Todo (Hayley#2#09/24/15): Put INI sections together to obey the standards better
Definition at line 78 of file Config.cpp.
References m_FileData.
Referenced by get(), and saveAll().
void Config::saveAll ()
Save all loaded configuration files with current settings.
Definition at line 118 of file Config.cpp.
References m_FileData, and save().
Referenced by get().
void Config::set (const std::string & file, const std::string & name, const std::string value)
Set a setting in the configuration database.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to set value of.
value String to set the setting to.
Definition at line 228 of file Config.cpp.
References m_FileData.
Referenced by LunarDriftProgram::LunarDriftProgram().
void Config::set (const std::string & file, const std::string & name, int value)
Set a setting in the configuration database.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to set value of.
value Signed integer to set the setting to.
Definition at line 239 of file Config.cpp.
References to_wstring().
void Config::set (const std::string & file, const std::string & name, bool value)
Set a setting in the configuration database.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to set value of.
value True/false value to set the setting to.
Definition at line 250 of file Config.cpp.
void Config::set (const std::string & file, const std::string & name, double value)
Set a setting in the configuration database.
Parameters
file Name of the INI file, without the .ini extension.
name Configuration setting to set value of.
value Double-precision decimal to set the setting to.
Definition at line 262 of file Config.cpp.
References to_wstring().
Member Data Documentation
std::map<std::string, std::map<std::string, std::string> > Config::m_FileData [private]
Settings database.
Definition at line 157 of file Config.h.
Referenced by get(), load(), save(), saveAll(), and set().
The documentation for this class was generated from the following files:
LunarDrift/engine/Config.h
LunarDrift/engine/Config.cpp