OpenGLException Class Reference
Exception raised whenever an OpenGL subsystem fails.
#include <OpenGLException.h>
Public Member Functions
OpenGLException (const std::string &report, GLenum glErrorCode)
Default constructor.
const std::string & getReport () const
GLenum getGLErrorCode () const
const std::string glErrorCodeToString (GLenum glErrorCode) const
Private Attributes
const std::string m_Report
const GLenum m_GLErrorCode
Detailed Description
Exception raised whenever an OpenGL subsystem fails.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 13 of file OpenGLException.h.
Constructor & Destructor Documentation
OpenGLException::OpenGLException (const std::string & report, GLenum glErrorCode)
Default constructor.
Parameters
report Error string
glErrorCode OpenGL API error code
Definition at line 4 of file OpenGLException.cpp.
Member Function Documentation
GLenum OpenGLException::getGLErrorCode () const [inline]
Definition at line 28 of file OpenGLException.h.
References glErrorCodeToString(), and m_GLErrorCode.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string& OpenGLException::getReport () const [inline]
Definition at line 26 of file OpenGLException.h.
References m_Report.
Referenced by WindowPC::renderingThread(), and WinMain().
const std::string OpenGLException::glErrorCodeToString (GLenum glErrorCode) const
Definition at line 24 of file OpenGLException.cpp.
References to_string().
Referenced by getGLErrorCode(), WindowPC::renderingThread(), and WinMain().
Member Data Documentation
const GLenum OpenGLException::m_GLErrorCode [private]
Definition at line 34 of file OpenGLException.h.
Referenced by getGLErrorCode().
const std::string OpenGLException::m_Report [private]
Definition at line 33 of file OpenGLException.h.
Referenced by getReport().
The documentation for this class was generated from the following files:
LunarDrift/engine/exceptions/OpenGLException.h
LunarDrift/engine/exceptions/OpenGLException.cpp