Keyboard Class Reference
Keyboard input representation object.
#include <Keyboard.h>
Public Member Functions
Keyboard ()
Default constructor.
virtual ~Keyboard ()
Default destructor.
void mapKeyToInput (Key key, const std::string &inputName)
Maps a given key to a `button-type` input class name.
void unmapKeyFromInputs (Key key)
Unmaps a given key from an input class name.
bool isKeyDown (const std::string &inputName)
Query if a given key associated with an input class name is down.
void setKeyDown (Key key)
Set a key into a down/pressed state.
void setKeyUp (Key key)
Set a key into an up/released state.
Private Attributes
std::vector< bool > m_KeyStates
Record of current key states.
std::map< Key, std::string > m_KeyInputMap
Record of key-input mapping.
Detailed Description
Keyboard input representation object.
This class manages abstract keyboard state whilst providing a mapping between hardware input state and abstract engine `button-type` input classes.
Author
Hayley Hatton
Date
13/03/2016
See also
InputMap
Definition at line 20 of file Keyboard.h.
Constructor & Destructor Documentation
Keyboard::Keyboard ()
Default constructor.
Definition at line 9 of file Keyboard.cpp.
References m_KeyStates.
Keyboard::~Keyboard () [virtual]
Default destructor.
Definition at line 14 of file Keyboard.cpp.
Member Function Documentation
bool Keyboard::isKeyDown (const std::string & inputName)
Query if a given key associated with an input class name is down.
Parameters
inputName Name of the input
Returns
True if pressed/down; false if released/up
Definition at line 31 of file Keyboard.cpp.
References m_KeyInputMap, and m_KeyStates.
Referenced by TestScene3D::step().
void Keyboard::mapKeyToInput (Key key, const std::string & inputName)
Maps a given key to a `button-type` input class name.
Parameters
key Key identifier
inputName Name of the input
Definition at line 21 of file Keyboard.cpp.
References m_KeyInputMap.
Referenced by LunarDriftProgram::LunarDriftProgram().
void Keyboard::setKeyDown (Key key)
Set a key into a down/pressed state.
Parameters
key Key identifier
Definition at line 43 of file Keyboard.cpp.
References MessageSystem::broadcast(), MessageSystem::getInstance(), m_KeyInputMap, and m_KeyStates.
Referenced by WindowPC::handleWin32EventQueue().
void Keyboard::setKeyUp (Key key)
Set a key into an up/released state.
Parameters
key Key identifier
Definition at line 53 of file Keyboard.cpp.
References MessageSystem::broadcast(), MessageSystem::getInstance(), m_KeyInputMap, and m_KeyStates.
Referenced by WindowPC::handleWin32EventQueue().
void Keyboard::unmapKeyFromInputs (Key key)
Unmaps a given key from an input class name.
Parameters
key Key identifier
inputName Name of the input
Definition at line 26 of file Keyboard.cpp.
References m_KeyInputMap.
Member Data Documentation
std::map<Key,std::string> Keyboard::m_KeyInputMap [private]
Record of key-input mapping.
Definition at line 64 of file Keyboard.h.
Referenced by isKeyDown(), mapKeyToInput(), setKeyDown(), setKeyUp(), and unmapKeyFromInputs().
std::vector<bool> Keyboard::m_KeyStates [private]
Record of current key states.
Definition at line 63 of file Keyboard.h.
Referenced by isKeyDown(), Keyboard(), setKeyDown(), and setKeyUp().
The documentation for this class was generated from the following files:
LunarDrift/engine/input/Keyboard.h
LunarDrift/engine/input/Keyboard.cpp