LifeTimeComponent Class Reference
Attach to a scene object to give it a time limit to its existence.
#include <LifeTimeComponent.h>
Public Member Functions
LifeTimeComponent (SceneObject *parent, std::weak_ptr< MetaManager > managers, double lifeSpan)
Default constructor.
virtual ~LifeTimeComponent ()
Default destructor.
void step (double dt) override
Step the simulation state.
void predraw (Context *context) override
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
void reset ()
Reset the timer to the original lifespan.
Private Attributes
const double m_InitialLifeSpan
The time to reset the lifespan to.
double m_LifeSpan
Time before an object dies in seconds.
bool m_Triggered
True if the timeout has activated.
Additional Inherited Members
Detailed Description
Attach to a scene object to give it a time limit to its existence.
This is currently setup to use Axis-Aligned Bounding Boxes, but the collision subsystem for it has been gutted.
Todo
Todo Setup collision geometry
Author
Hayley Hatton
Date
06/03/2016
See also
CollisionManager
Definition at line 16 of file LifeTimeComponent.h.
Constructor & Destructor Documentation
LifeTimeComponent::LifeTimeComponent (SceneObject * parent, std::weak_ptr< MetaManager > managers, double lifeSpan)
Default constructor.
Parameters
parent Pointer to the scene object to attach component to
managers Metamanager for accessing scene's managers
lifeSpan Time in seconds until the timeout is fired
Definition at line 7 of file LifeTimeComponent.cpp.
LifeTimeComponent::~LifeTimeComponent () [virtual]
Default destructor.
Definition at line 18 of file LifeTimeComponent.cpp.
Member Function Documentation
void LifeTimeComponent::predraw (Context * context) [inline], [override], [virtual]
Called before the renderer draws the scene This allows the scene objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Implements SceneObjectComponent.
Definition at line 47 of file LifeTimeComponent.h.
References reset().
void LifeTimeComponent::reset ()
Reset the timer to the original lifespan.
Definition at line 42 of file LifeTimeComponent.cpp.
References m_InitialLifeSpan, m_LifeSpan, and m_Triggered.
Referenced by predraw().
void LifeTimeComponent::step (double dt) [override], [virtual]
Step the simulation state.
Parameters
dt Delta-time since last step call in seconds
Implements SceneObjectComponent.
Definition at line 23 of file LifeTimeComponent.cpp.
References SceneObjectComponent::getParent(), m_LifeSpan, m_Triggered, and IMessageListener::onMessage().
Member Data Documentation
const double LifeTimeComponent::m_InitialLifeSpan [private]
The time to reset the lifespan to.
Definition at line 53 of file LifeTimeComponent.h.
Referenced by reset().
double LifeTimeComponent::m_LifeSpan [private]
Time before an object dies in seconds.
Definition at line 54 of file LifeTimeComponent.h.
Referenced by reset(), and step().
bool LifeTimeComponent::m_Triggered [private]
True if the timeout has activated.
Definition at line 55 of file LifeTimeComponent.h.
Referenced by reset(), and step().
The documentation for this class was generated from the following files:
LunarDrift/engine/components/LifeTimeComponent.h
LunarDrift/engine/components/LifeTimeComponent.cpp