Scene Class Reference
Scene container for managing and drawing 3D environments.
#include <Scene.h>
Public Member Functions
Scene (Context *context)
Default constructor.
virtual ~Scene ()
Default destructor.
void getObjects (std::list< std::shared_ptr< SceneObject > > *objects)
Retrieve the list of objects in the scene.
const std::weak_ptr< Camera > getActiveCamera () const
Access the currently active camera.
virtual void setSize (GLsizei width, GLsizei height)
Called to update scene elements with the viewport information.
virtual void step (double dt)
Step the scene's simulation state.
virtual void predraw (Context *context)
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
Protected Member Functions
void addObject (std::shared_ptr< SceneObject > object)
Add an object to be managed by the scene.
void setActiveCamera (std::shared_ptr< Camera > camera)
Set the active camera for the scene.
std::weak_ptr< MetaManager > getManagers ()
Private Attributes
std::shared_ptr< MetaManager > m_Managers
std::shared_ptr< Camera > m_ActiveCamera
Camera currently in use.
Detailed Description
Scene container for managing and drawing 3D environments.
Precondition
A valid OpenGL context must be present to the program
Author
Hayley Hatton
Date
06/03/2016
Definition at line 15 of file Scene.h.
Constructor & Destructor Documentation
Scene::Scene (Context * context)
Default constructor.
Parameters
context Graphics context
Definition at line 6 of file Scene.cpp.
References m_Managers.
Scene::~Scene () [virtual]
Default destructor.
Definition at line 14 of file Scene.cpp.
Member Function Documentation
void Scene::addObject (std::shared_ptr< SceneObject > object) [protected]
Add an object to be managed by the scene.
Parameters
object Smart pointer to the scene object
Definition at line 28 of file Scene.cpp.
References SceneObjectManager::addSceneObject(), and m_Managers.
Referenced by TestScene3D::TestScene3D().
const std::weak_ptr< Camera > Scene::getActiveCamera () const
Access the currently active camera.
Returns
Managed pointer to the currently active camera
Definition at line 62 of file Scene.cpp.
References m_ActiveCamera.
Referenced by TestScene3D::setSize(), and TestScene3D::step().
std::weak_ptr<MetaManager> Scene::getManagers () [inline], [protected]
Definition at line 75 of file Scene.h.
References m_Managers.
Referenced by TestScene3D::TestScene3D().
void Scene::getObjects (std::list< std::shared_ptr< SceneObject > > * objects)
Retrieve the list of objects in the scene.
Parameters
objects Pointer to list to fill with scene objects
Definition at line 20 of file Scene.cpp.
References SceneObjectManager::getObjects(), and m_Managers.
void Scene::predraw (Context * context) [virtual]
Called before the renderer draws the scene This allows the scene and its constituent objects to do updates that require a graphics context before the graphical state is drawn.
Parameters
context Graphics context
Reimplemented in TestScene3D.
Definition at line 49 of file Scene.cpp.
References m_Managers, and SceneObjectManager::predraw().
Referenced by TestScene3D::predraw().
void Scene::setActiveCamera (std::shared_ptr< Camera > camera) [protected]
Set the active camera for the scene.
Parameters
camera Smart pointer to the camera to make active
Definition at line 57 of file Scene.cpp.
References m_ActiveCamera.
Referenced by TestScene3D::TestScene3D().
void Scene::setSize (GLsizei width, GLsizei height) [virtual]
Called to update scene elements with the viewport information.
Parameters
width Width of the viewport in pixels
height Height of the viewport in pixels
Reimplemented in TestScene3D.
Definition at line 67 of file Scene.cpp.
void Scene::step (double dt) [virtual]
Step the scene's simulation state.
Parameters
dt Delta-time since last step call in seconds
Reimplemented in TestScene3D.
Definition at line 36 of file Scene.cpp.
References CollisionManager::doCollisions(), m_Managers, and SceneObjectManager::step().
Referenced by TestScene3D::step().
Member Data Documentation
std::shared_ptr<Camera> Scene::m_ActiveCamera [private]
Camera currently in use.
Definition at line 79 of file Scene.h.
Referenced by getActiveCamera(), and setActiveCamera().
std::shared_ptr<MetaManager> Scene::m_Managers [private]
Definition at line 78 of file Scene.h.
Referenced by addObject(), getManagers(), getObjects(), predraw(), Scene(), and step().
The documentation for this class was generated from the following files:
LunarDrift/engine/containers/Scene.h
LunarDrift/engine/containers/Scene.cpp