Renderer Class Reference
Abstract renderer for drawing scenes with a given graphics context.
#include <Renderer.h>
Public Member Functions
Renderer (Context *context, GLsizei width, GLsizei height)
Default constructor.
virtual ~Renderer ()
Default destructor.
void getDimensions (GLsizei *width, GLsizei *height) const
Access the dimensions of the full rendering context.
virtual void preFrame (Context *context, std::shared_ptr< Scene > scene)
Called before the frame is drawn; useful for setting up the frame.
virtual void frame (Context *context, std::shared_ptr< Scene > scene)
Called to draw the frame.
virtual void postFrame (Context *context, std::shared_ptr< Scene > scene)
Called after the frame is drawn; useful for posting the frame.
void setClearColor (const glm::vec4 &color)
void resize (GLsizei width, GLsizei height)
Resize the renderer.
Protected Member Functions
void setSize (Context *context, std::shared_ptr< Scene > scene)
Update the viewport and echo changes to the scene.
virtual std::shared_ptr< ShaderManager > loadStandardShaders (Context *context)=0
Create and return a shader manager containing the standard shaders.
void load (Context *context)
Load the renderer.
void updateShaderStates (Context *context, std::shared_ptr< Scene > scene, std::shared_ptr< ShaderManager > shaders)
Update the shader states of all the shaders in a shader manager.
void drawScene (Context *context, std::shared_ptr< Scene > scene, std::shared_ptr< ShaderManager > shaders)
Draw a scene using a given shader manager.
Private Attributes
GLsizei m_WidthPx
GLsizei m_HeightPx
bool m_Resized
glm::vec4 m_ClearColor
std::shared_ptr< ShaderManager > m_StandardShaders
Detailed Description
Abstract renderer for drawing scenes with a given graphics context.
Author
Hayley Hatton
Date
20/02/2016
Definition at line 13 of file Renderer.h.
Constructor & Destructor Documentation
Renderer::Renderer (Context * context, GLsizei width, GLsizei height)
Default constructor.
Parameters
context Graphics context
width Width of context in pixels
height Height of context in pixels
Definition at line 4 of file Renderer.cpp.
References f.
Renderer::~Renderer () [virtual]
Default destructor.
Definition at line 12 of file Renderer.cpp.
Member Function Documentation
void Renderer::drawScene (Context * context, std::shared_ptr< Scene > scene, std::shared_ptr< ShaderManager > shaders) [protected]
Draw a scene using a given shader manager.
Parameters
context Graphics context
scene Smart pointer to the scene instance to draw
shaders Smart pointer to the shader manager to draw scene with
Definition at line 68 of file Renderer.cpp.
Referenced by frame(), and setClearColor().
void Renderer::frame (Context * context, std::shared_ptr< Scene > scene) [virtual]
Called to draw the frame.
Parameters
context Graphics context
scene Smart pointer to the scene to render
Definition at line 84 of file Renderer.cpp.
References drawScene(), m_Resized, m_StandardShaders, setSize(), and updateShaderStates().
void Renderer::getDimensions (GLsizei * width, GLsizei * height) const
Access the dimensions of the full rendering context.
Parameters
width Pointer to store width in pixels
height Pointer to store height in pixels
Definition at line 18 of file Renderer.cpp.
References m_HeightPx, and m_WidthPx.
Referenced by setSize().
void Renderer::load (Context * context) [protected]
Load the renderer.
Parameters
context Graphics context
Definition at line 101 of file Renderer.cpp.
References loadStandardShaders(), and m_StandardShaders.
Referenced by GameRenderer::GameRenderer(), and setClearColor().
virtual std::shared_ptr<ShaderManager> Renderer::loadStandardShaders (Context * context) [protected], [pure virtual]
Create and return a shader manager containing the standard shaders.
Returns
Managed pointer of a default shader manager
Implemented in GameRenderer.
Referenced by load(), and setClearColor().
void Renderer::postFrame (Context * context, std::shared_ptr< Scene > scene) [virtual]
Called after the frame is drawn; useful for posting the frame.
Parameters
context Graphics context
scene Smart pointer to the scene to render
Definition at line 96 of file Renderer.cpp.
void Renderer::preFrame (Context * context, std::shared_ptr< Scene > scene) [virtual]
Called before the frame is drawn; useful for setting up the frame.
Parameters
context Graphics context
scene Smart pointer to the scene to render
Definition at line 46 of file Renderer.cpp.
References m_ClearColor.
void Renderer::resize (GLsizei width, GLsizei height)
Resize the renderer.
Parameters
width New width of GL context in pixels
height New height of GL context in pixels
Definition at line 24 of file Renderer.cpp.
References m_HeightPx, m_Resized, and m_WidthPx.
Referenced by setClearColor().
void Renderer::setClearColor (const glm::vec4 & color) [inline]
Definition at line 56 of file Renderer.h.
References drawScene(), load(), loadStandardShaders(), m_ClearColor, resize(), setSize(), and updateShaderStates().
Referenced by GameRenderer::GameRenderer().
void Renderer::setSize (Context * context, std::shared_ptr< Scene > scene) [protected]
Update the viewport and echo changes to the scene.
Parameters
context Graphics context
scene Smart pointer to the scene to resize
Definition at line 31 of file Renderer.cpp.
References getDimensions(), h, m_Resized, and w.
Referenced by frame(), and setClearColor().
void Renderer::updateShaderStates (Context * context, std::shared_ptr< Scene > scene, std::shared_ptr< ShaderManager > shaders) [protected]
Update the shader states of all the shaders in a shader manager.
Parameters
context Graphics context
scene Smart pointer to the scene instance to use
shaders Smart pointer to the shader manager to update states with
Definition at line 55 of file Renderer.cpp.
Referenced by frame(), and setClearColor().
Member Data Documentation
glm::vec4 Renderer::m_ClearColor [private]
Definition at line 111 of file Renderer.h.
Referenced by preFrame(), and setClearColor().
GLsizei Renderer::m_HeightPx [private]
Definition at line 109 of file Renderer.h.
Referenced by getDimensions(), and resize().
bool Renderer::m_Resized [private]
Definition at line 110 of file Renderer.h.
Referenced by frame(), resize(), and setSize().
std::shared_ptr<ShaderManager> Renderer::m_StandardShaders [private]
Definition at line 112 of file Renderer.h.
Referenced by frame(), and load().
GLsizei Renderer::m_WidthPx [private]
Definition at line 109 of file Renderer.h.
Referenced by getDimensions(), and resize().
The documentation for this class was generated from the following files:
LunarDrift/engine/graphics/renderers/Renderer.h
LunarDrift/engine/graphics/renderers/Renderer.cpp